In [ ]:
import json
import pandas as pd
from pathlib import Path

import importlib
import sys
sys.path.append('../') # these two lines allow the notebook to find the path to the source code contained in 'src'
from features import data_utils as du
from features import data_pipeline as dp

# Reload
importlib.reload(du)
importlib.reload(dp)

parent_folder = Path("../..") # go 2 folder up: "../.."
data_folder = parent_folder / "data"
input_path_of_json = data_folder / "patients_data_log.json"
df_data_log = pd.read_json(input_path_of_json)

In [ ]:
df_data_log

In [8]:
patient_id = df_data_log["PatientID"].to_list()
print(patient_id)

['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P009', 'P010', 'P011', 'P012', 'P013', 'P014', 'P015', 'P016', 'P017', 'P018', 'P019', 'P020']

In [20]:
patients_data_folder = data_folder / "PatientsData"

In [11]:
prefix

'P001_'

# find the folder
prefix = patient_id[0] + "_"

matching_dirs = [
    p for p in patients_data_folder.rglob("*")
    if p.is_dir() and p.name.lower().startswith(prefix.lower())
]

current_patient_data_folder = matching_dirs[0] if matching_dirs else None
current_patient_data_folder

In [ ]:
current_patient_data_folder = data_utils.find_patient_folder(patients_data_folder=patients_data_folder,
                         patient_id=patient_id[0])

WindowsPath('../../data/PatientsData/p001_20260502_113117')

In [ ]:
"""folder_path = current_patient_data_folder

csv_files = [
    file.name
    for file in folder_path.glob("*.csv")
]

print(csv_files)"""

['20260502_113117_01_Tutorial_events.csv', '20260502_113117_01_Tutorial_trajectory.csv', '20260502_113117_02_ObjectRecognition_events.csv', '20260502_113117_02_ObjectRecognition_trajectory.csv', '20260502_113117_03_Visuospatial_events.csv', '20260502_113117_03_Visuospatial_trajectory.csv', '20260502_113117_04_Memory_events.csv', '20260502_113117_04_Memory_trajectory.csv', '20260502_113117_SESSION_SUMMARY.csv']

In [28]:
list_of_csv_files = data_utils.find_csv_file(folder_path=current_patient_data_folder)

In [57]:
output_path_of_csv

WindowsPath('../../data/PatientsData/p001_20260502_113117/clean_data/cleaned_20260502_113117_01_Tutorial_events.csv')

In [63]:
for csv_file in list_of_csv_files:
    
    input_path_of_csv = current_patient_data_folder / csv_file
    #print(input_path_of_csv)
    Path(current_patient_data_folder / "clean_data").mkdir(exist_ok=True)
    
    output_path_of_csv = current_patient_data_folder / 'clean_data' / f"cleaned_{csv_file}"

    x = data_utils.cleaning_csv_file(csv_path_to_read=input_path_of_csv, 
                                 csv_path_to_write=output_path_of_csv)

    break

..\..\data\PatientsData\p001_20260502_113117\20260502_113117_01_Tutorial_events.csv
..\..\data\PatientsData\p001_20260502_113117\clean_data\cleaned_20260502_113117_01_Tutorial_events.csv

In [53]:
x

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log
0,2026-05-02 11:31:17.628,0.000,Default,PHASE_START,,,,0.000,0.000,Phase=01_Tutorial,"[Section=Default, SessionID=20260502_113117, P..."
1,2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,,,0.000,0.000,Section=Default,[Panel=WelcomePanel]
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
3,2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
...,...,...,...,...,...,...,...,...,...,...,...
73,2026-05-02 11:32:09.007,46.040,GrabPractice,SECTION_END,,,,21.000,0.000,Section=GrabPractice,[Duration=21.00s]
74,2026-05-02 11:32:09.007,46.040,Completion,SECTION_START,,,,0.000,0.000,Section=Completion,[PhaseTime=46.04s]
75,2026-05-02 11:32:09.008,46.040,Completion,TUTORIAL_COMPLETE,,,,0.000,0.000,Section=Completion,"[ObjectsPlaced=3, ButtonsPressed=2]"
76,2026-05-02 11:32:12.007,49.040,Completion,SCORING_SUMMARY,,,,0.000,0.000,Section=Completion,"[Correct=0, Incorrect=0, Total=0, Accuracy=0.0..."
77,2026-05-02 11:32:12.007,49.040,Completion,PHASE_END,,,,49.040,0.000,Samples=442,[Events=77]

In [44]:
x

[[['2026-05-02 11:31:17.628',
   '0.000',
   'Default',
   'PHASE_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Phase=01_Tutorial',
   ['Section=Default',
    'SessionID=20260502_113117',
    'PatientID=',
    'SampleRate=10Hz',
    'Device=Oculus Quest 3',
    'GazeTrackerActive=True']],
  ['2026-05-02 11:31:17.630',
   '0.000',
   'Default',
   'PANEL_SHOWN',
   'WelcomePanel',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Panel=WelcomePanel']],
  ['2026-05-02 11:31:22.971',
   '0.000',
   'Default',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverCount=1']],
  ['2026-05-02 11:31:23.918',
   '0.952',
   'Default',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverDuration=0.95s']],
  ['2026-05-02 11:31:26.072',
   '3.106',
   'Default',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverCount=2']],
  ['2026-05-02 11:31:26.183',
   '3.217',
   'Default',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverDuration=0.11s']],
  ['2026-05-02 11:31:26.378',
   '3.411',
   'Default',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverCount=3']],
  ['2026-05-02 11:31:26.697',
   '3.731',
   'Default',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverDuration=0.32s']],
  ['2026-05-02 11:31:28.907',
   '5.940',
   'Default',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverCount=4']],
  ['2026-05-02 11:31:29.448',
   '6.483',
   'Default',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverDuration=0.54s']],
  ['2026-05-02 11:31:35.603',
   '12.637',
   'Default',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverCount=5']],
  ['2026-05-02 11:31:37.895',
   '14.930',
   'Default',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverDuration=2.29s']],
  ['2026-05-02 11:31:38.423',
   '15.457',
   'Default',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverCount=6']],
  ['2026-05-02 11:31:38.909',
   '15.943',
   'Default',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverDuration=0.49s']],
  ['2026-05-02 11:31:39.381',
   '16.415',
   'Default',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverCount=7']],
  ['2026-05-02 11:31:39.979',
   '17.013',
   'Default',
   'BUTTON_PRESSED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'PressTime=0.60s']],
  ['2026-05-02 11:31:40.200',
   '17.235',
   'Default',
   'BUTTON_RELEASED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'PressDuration=0.222s']],
  ['2026-05-02 11:31:40.205',
   '17.235',
   'Default',
   'PANEL_DISMISSED',
   'WelcomePanel',
   '',
   '',
   '17.235',
   '0.000',
   'Section=Default',
   ['Panel=WelcomePanel', 'ReadingTime=17.23s']],
  ['2026-05-02 11:31:40.206',
   '17.235',
   'Default',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=Default',
   ['Button=StartTutorialButton[TutorialWelcome]', 'HoverDuration=0.82s']],
  ['2026-05-02 11:31:40.208',
   '17.235',
   'Default',
   'SECTION_END',
   '',
   '',
   '',
   '17.235',
   '0.000',
   'Section=Default',
   ['Duration=17.23s']]],
 [['2026-05-02 11:31:40.208',
   '17.235',
   'ButtonSelection',
   'SECTION_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['PhaseTime=17.23s']],
  ['2026-05-02 11:31:40.209',
   '17.235',
   'ButtonSelection',
   'PANEL_SHOWN',
   'ButtonInstructionPanel',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Panel=ButtonInstructionPanel']],
  ['2026-05-02 11:31:40.209',
   '17.235',
   'ButtonSelection',
   'BUTTON_CLICKED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=StartTutorialButton[TutorialWelcome]',
    'HoverDuration=0.82s',
    'TotalHovers=7']],
  ['2026-05-02 11:31:44.409',
   '21.443',
   'ButtonSelection',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton1[TutorialButtonSelection]', 'HoverCount=1']],
  ['2026-05-02 11:31:45.506',
   '22.540',
   'ButtonSelection',
   'BUTTON_PRESSED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton1[TutorialButtonSelection]', 'PressTime=1.10s']],
  ['2026-05-02 11:31:45.659',
   '22.693',
   'ButtonSelection',
   'BUTTON_RELEASED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton1[TutorialButtonSelection]',
    'PressDuration=0.153s']],
  ['2026-05-02 11:31:45.660',
   '22.693',
   'ButtonSelection',
   'BUTTON_PRESSED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=1', 'PressCount=1']],
  ['2026-05-02 11:31:45.661',
   '22.693',
   'ButtonSelection',
   'BUTTON_CLICKED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton1[TutorialButtonSelection]',
    'HoverDuration=1.25s',
    'TotalHovers=1']],
  ['2026-05-02 11:31:45.923',
   '22.956',
   'ButtonSelection',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton1[TutorialButtonSelection]', 'HoverDuration=1.51s']],
  ['2026-05-02 11:31:46.130',
   '23.165',
   'ButtonSelection',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton2[TutorialButtonSelection]', 'HoverCount=1']],
  ['2026-05-02 11:31:46.881',
   '23.915',
   'ButtonSelection',
   'BUTTON_PRESSED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton2[TutorialButtonSelection]', 'PressTime=0.75s']],
  ['2026-05-02 11:31:47.006',
   '24.040',
   'ButtonSelection',
   'BUTTON_RELEASED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton2[TutorialButtonSelection]',
    'PressDuration=0.124s']],
  ['2026-05-02 11:31:47.008',
   '24.040',
   'ButtonSelection',
   'BUTTON_PRESSED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=2', 'PressCount=2']],
  ['2026-05-02 11:31:47.008',
   '24.040',
   'ButtonSelection',
   'PANEL_DISMISSED',
   'ButtonInstructionPanel',
   '',
   '',
   '6.805',
   '0.000',
   'Section=ButtonSelection',
   ['Panel=ButtonInstructionPanel', 'ReadingTime=6.80s']],
  ['2026-05-02 11:31:47.008',
   '24.040',
   'ButtonSelection',
   'BUTTON_SECTION_COMPLETE',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['CompletionTime=6.80s']],
  ['2026-05-02 11:31:47.009',
   '24.040',
   'ButtonSelection',
   'BUTTON_CLICKED',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton2[TutorialButtonSelection]',
    'HoverDuration=0.87s',
    'TotalHovers=1']],
  ['2026-05-02 11:31:47.242',
   '24.276',
   'ButtonSelection',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton2[TutorialButtonSelection]', 'HoverDuration=1.11s']],
  ['2026-05-02 11:31:47.297',
   '24.331',
   'ButtonSelection',
   'BUTTON_HOVER_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton2[TutorialButtonSelection]', 'HoverCount=2']],
  ['2026-05-02 11:31:47.381',
   '24.415',
   'ButtonSelection',
   'BUTTON_HOVER_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=ButtonSelection',
   ['Button=PracticeButton2[TutorialButtonSelection]', 'HoverDuration=0.08s']],
  ['2026-05-02 11:31:48.008',
   '25.040',
   'ButtonSelection',
   'SECTION_END',
   '',
   '',
   '',
   '7.805',
   '0.000',
   'Section=ButtonSelection',
   ['Duration=7.80s']]],
 [['2026-05-02 11:31:48.008',
   '25.040',
   'GrabPractice',
   'SECTION_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['PhaseTime=25.04s']],
  ['2026-05-02 11:31:48.009',
   '25.040',
   'GrabPractice',
   'PANEL_SHOWN',
   'GrabInstructionPanel',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Panel=GrabInstructionPanel']],
  ['2026-05-02 11:31:48.023',
   '25.061',
   'GrabPractice',
   'HOVER_START',
   'Cube',
   '',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['IsCorrect=False']],
  ['2026-05-02 11:31:48.046',
   '25.080',
   'GrabPractice',
   'HOVER_END',
   'Cube',
   '',
   'FALSE',
   '0.019',
   '0.000',
   'Section=GrabPractice',
   ['HoverDuration=0.019s']],
  ['2026-05-02 11:31:48.073',
   '25.107',
   'GrabPractice',
   'HOVER_START',
   'Cube',
   '',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['IsCorrect=False']],
  ['2026-05-02 11:31:49.756',
   '26.790',
   'GrabPractice',
   'HOVER_END',
   'Cube',
   '',
   'FALSE',
   '1.683',
   '0.000',
   'Section=GrabPractice',
   ['HoverDuration=1.683s']],
  ['2026-05-02 11:31:56.714',
   '33.749',
   'GrabPractice',
   'HOVER_START',
   'Sphere',
   '',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['IsCorrect=False']],
  ['2026-05-02 11:31:57.122',
   '34.151',
   'GrabPractice',
   'GRAB_START',
   'Sphere',
   'Right',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Position=(0.84', ' 1.18', ' -0.01)', 'WasHovered=True']],
  ['2026-05-02 11:31:58.603',
   '35.637',
   'GrabPractice',
   'GRAB_RELEASE',
   'Sphere',
   'Right',
   'FALSE',
   '1.485',
   '0.172',
   'Section=GrabPractice',
   ['ReleasePos=(1.00',
    ' 1.22',
    ' -0.01)',
    'GripDuration=1.485s',
    'WasHovered=True']],
  ['2026-05-02 11:31:58.769',
   '35.803',
   'GrabPractice',
   'HOVER_END',
   'Sphere',
   '',
   'FALSE',
   '2.055',
   '0.000',
   'Section=GrabPractice',
   ['HoverDuration=2.055s']],
  ['2026-05-02 11:31:59.200',
   '36.234',
   'GrabPractice',
   'HOVER_START',
   'Sphere',
   '',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['IsCorrect=False']],
  ['2026-05-02 11:32:00.047',
   '37.081',
   'GrabPractice',
   'GRAB_START',
   'Sphere',
   'Right',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Position=(0.84',
    ' 1.18',
    ' -0.01)',
    'WasHovered=True',
    'InterObjectTime=2.93s']],
  ['2026-05-02 11:32:01.173',
   '38.207',
   'GrabPractice',
   'GRAB_RELEASE',
   'Sphere',
   'Right',
   'FALSE',
   '1.125',
   '0.219',
   'Section=GrabPractice',
   ['ReleasePos=(1.05',
    ' 1.19',
    ' -0.02)',
    'GripDuration=1.125s',
    'WasHovered=True']],
  ['2026-05-02 11:32:01.190',
   '38.209',
   'GrabPractice',
   'HOVER_END',
   'Sphere',
   '',
   'FALSE',
   '1.975',
   '0.000',
   'Section=GrabPractice',
   ['HoverDuration=1.975s']],
  ['2026-05-02 11:32:01.191',
   '38.209',
   'GrabPractice',
   'GRAB_PRACTICE_PLACEMENT',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['ObjectsPlaced=1', 'Required=3']],
  ['2026-05-02 11:32:02.936',
   '39.970',
   'GrabPractice',
   'HOVER_START',
   'Cylinder',
   '',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['IsCorrect=False']],
  ['2026-05-02 11:32:03.311',
   '40.346',
   'GrabPractice',
   'GRAB_START',
   'Cylinder',
   'Right',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Position=(0.83',
    ' 1.23',
    ' -0.26)',
    'WasHovered=True',
    'InterObjectTime=3.26s']],
  ['2026-05-02 11:32:03.631',
   '40.664',
   'GrabPractice',
   'GAZE_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Target=Cylinder', 'Distance=1.33m']],
  ['2026-05-02 11:32:03.853',
   '40.887',
   'GrabPractice',
   'GAZE_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Target=Cylinder', 'DwellTime=0.22s', 'Distance=1.33m']],
  ['2026-05-02 11:32:03.964',
   '40.997',
   'GrabPractice',
   'GAZE_START',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Target=Cylinder', 'Distance=1.42m']],
  ['2026-05-02 11:32:04.186',
   '41.220',
   'GrabPractice',
   'GAZE_END',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Target=Cylinder', 'DwellTime=0.22s', 'Distance=1.42m']],
  ['2026-05-02 11:32:04.797',
   '41.831',
   'GrabPractice',
   'GRAB_RELEASE',
   'Cylinder',
   'Right',
   'FALSE',
   '1.486',
   '0.299',
   'Section=GrabPractice',
   ['ReleasePos=(0.81',
    ' 1.25',
    ' -0.56)',
    'GripDuration=1.486s',
    'WasHovered=True']],
  ['2026-05-02 11:32:04.825',
   '41.849',
   'GrabPractice',
   'HOVER_END',
   'Cylinder',
   '',
   'FALSE',
   '1.879',
   '0.000',
   'Section=GrabPractice',
   ['HoverDuration=1.879s']],
  ['2026-05-02 11:32:04.826',
   '41.849',
   'GrabPractice',
   'GRAB_PRACTICE_PLACEMENT',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['ObjectsPlaced=2', 'Required=3']],
  ['2026-05-02 11:32:06.117',
   '43.151',
   'GrabPractice',
   'HOVER_START',
   'Cube',
   '',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['IsCorrect=False']],
  ['2026-05-02 11:32:06.159',
   '43.193',
   'GrabPractice',
   'HOVER_END',
   'Cube',
   '',
   'FALSE',
   '0.042',
   '0.000',
   'Section=GrabPractice',
   ['HoverDuration=0.042s']],
  ['2026-05-02 11:32:06.172',
   '43.207',
   'GrabPractice',
   'HOVER_START',
   'Cube',
   '',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['IsCorrect=False']],
  ['2026-05-02 11:32:06.506',
   '43.540',
   'GrabPractice',
   'GRAB_START',
   'Cube',
   'Right',
   'FALSE',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['Position=(0.84',
    ' 1.18',
    ' 0.21)',
    'WasHovered=True',
    'InterObjectTime=3.19s']],
  ['2026-05-02 11:32:07.992',
   '45.027',
   'GrabPractice',
   'GRAB_RELEASE',
   'Cube',
   'Right',
   'FALSE',
   '1.487',
   '0.347',
   'Section=GrabPractice',
   ['ReleasePos=(0.79',
    ' 1.22',
    ' 0.55)',
    'GripDuration=1.487s',
    'WasHovered=True']],
  ['2026-05-02 11:32:08.007',
   '45.029',
   'GrabPractice',
   'HOVER_END',
   'Cube',
   '',
   'FALSE',
   '1.822',
   '0.000',
   'Section=GrabPractice',
   ['HoverDuration=1.822s']],
  ['2026-05-02 11:32:08.008',
   '45.029',
   'GrabPractice',
   'GRAB_PRACTICE_PLACEMENT',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['ObjectsPlaced=3', 'Required=3']],
  ['2026-05-02 11:32:09.006',
   '46.040',
   'GrabPractice',
   'PANEL_DISMISSED',
   'GrabInstructionPanel',
   '',
   '',
   '21.000',
   '0.000',
   'Section=GrabPractice',
   ['Panel=GrabInstructionPanel', 'ReadingTime=21.00s']],
  ['2026-05-02 11:32:09.007',
   '46.040',
   'GrabPractice',
   'GRAB_SECTION_COMPLETE',
   '',
   '',
   '',
   '0.000',
   '0.000',
   'Section=GrabPractice',
   ['CompletionTime=21.00s', 'ObjectsPlaced=3']],
  ['2026-05-02 11:32:09.007',
   '46.040',
   'GrabPractice',
   'SECTION_END',
   '',
   '',
   '',
   '21.000',
   '0.000',
   'Section=GrabPractice',
   ['Duration=21.00s']]]]

In [32]:
messy_data_frame

,SessionID,PatientID,Date,TotalDuration_s,Phase,Completed,Correct,Incorrect,Accuracy_pct,PhaseDuration_s
0,20260502_113117,-,2026-05-02,49.0,01_Tutorial,True,0,0,0.0,49.0
1,20260502_113117,-,2026-05-02,49.0,02_ObjectRecognition,False,0,0,0.0,0.0
2,20260502_113117,-,2026-05-02,49.0,03_Visuospatial,False,0,0,0.0,0.0
3,20260502_113117,-,2026-05-02,49.0,04_Memory,False,0,0,0.0,0.0