# 0.Library

In [69]:
import pandas as pd
from pathlib import Path
import re

import importlib
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp
from features import general_func as gf
import constants_data as cd

# Reload
importlib.reload(du)
importlib.reload(dp)
importlib.reload(gf)
importlib.reload(cd)

# 1. Paths and Constants

In [62]:
# Constants and paths
parent_folder = Path("../..") # go 2 folder up= "../.."
data_folder   = parent_folder / "data"
input_path_of_json   = data_folder / "patients_data_log.json"
patients_data_log_df = pd.read_json(input_path_of_json)

patient_ids          = patients_data_log_df["PatientID"].to_list()
patients_data_folder = data_folder / "PatientsData"

patient_dict = cd.patient_dict
phase_name_list = cd.phase_name_list
event_empty_dictionaries = [cd.reading_time_dict, cd.hover_dict, cd.press_dict, cd.grab_dict, cd.gaze_dict, cd.behavior_dict, cd.temporal_dict]
extra_features_empty_dictionaries = [cd.obj_recognition_dict, cd.visuospatial_dict, cd.memory_dict]
trajectory_empty_dictionaries = [cd.headset_dict, cd.controller_dict]

# 2. Creating extracted_features_df columns

In [63]:
basic_event_col = []
for value in event_empty_dictionaries:
    column = value.keys()
    basic_event_col += list(column)

trajectory_col = []
for value in trajectory_empty_dictionaries:
    column = value.keys()
    trajectory_col += list(column)

In [64]:
all_phase_column_lists = []
all_phase_column_lists.append(list(patient_dict.keys())) 

for phase in phase_name_list:
    phase_column_list = []
    
    # add event + extra columns
    for value in basic_event_col:
        
        phase_column = phase + '_' + value 
        phase_column_list.append(phase_column)

    if phase == phase_name_list[1]: # ObjectRecognition
        phase_column_list.extend(extra_features_empty_dictionaries[0].keys())

    elif phase == phase_name_list[2]: # Visuospatial
        phase_column_list.extend(extra_features_empty_dictionaries[1].keys())

    elif phase == phase_name_list[3]: # Memory
        phase_column_list.extend(extra_features_empty_dictionaries[2].keys())
    
    # add trajectory
    for value in trajectory_col:
        
        phase_column = phase + '_' + value 
        phase_column_list.append(phase_column)
    
    all_phase_column_lists.append(phase_column_list)

all_phase_column_lists

[['Paitent_id',
  'Age',
  'Gender',
  'dominant_hand',
  'Sessions_Completed_out_of_4',
  'Help_Rating_out_of_5'],
 ['Tutorial_total_reading_time',
  'Tutorial_mean_reading_time',
  'Tutorial_max_reading_time',
  'Tutorial_median_reading_time',
  'Tutorial_std_reading_time',
  'Tutorial_intensity_reading_time',
  'Tutorial_total_count_hover',
  'Tutorial_total_duration_hover',
  'Tutorial_mean_duration_hover',
  'Tutorial_max_duration_hover',
  'Tutorial_median_duration_hover',
  'Tutorial_std_duration_hover',
  'Tutorial_intensity_hover',
  'Tutorial_total_count_press',
  'Tutorial_total_duration_press',
  'Tutorial_mean_duration_press',
  'Tutorial_max_duration_press',
  'Tutorial_median_duration_press',
  'Tutorial_std_duration_press',
  'Tutorial_intensity_press',
  'Tutorial_total_count_grab',
  'Tutorial_total_duration_grab',
  'Tutorial_mean_duration_grab',
  'Tutorial_max_duration_grab',
  'Tutorial_median_duration_grab',
  'Tutorial_std_duration_grab',
  'Tutorial_intensity_grab',
  'Tutorial_total_count_gaze',
  'Tutorial_total_duration_gaze',
  'Tutorial_mean_duration_gaze',
  'Tutorial_max_duration_gaze',
  'Tutorial_median_duration_gaze',
  'Tutorial_std_duration_gaze',
  'Tutorial_intensity_gaze',
  'Tutorial_hover_vs_reading_time_ratio',
  'Tutorial_hover_vs_active_interaction_ratio',
  'Tutorial_interaction_fraction',
  'Tutorial_decision_latency',
  'Tutorial_clicks_per_second',
  'Tutorial_hovers_per_click',
  'Tutorial_time_before_first_press',
  'Tutorial_time_before_first_hover',
  'Tutorial_head_total_distance',
  'Tutorial_HMD_X_std',
  'Tutorial_HMD_Y_std',
  'Tutorial_HMD_Z_std',
  'Tutorial_HMD_X_range',
  'Tutorial_HMD_Y_range',
  'Tutorial_HMD_Z_range',
  'Tutorial_mean_head_speed_in_distance',
  'Tutorial_max_head_speed_in_distance',
  'Tutorial_std_head_speed_in_distance',
  'Tutorial_head_total_orientation',
  'Tutorial_Yaw_std',
  'Tutorial_Pitch_std',
  'Tutorial_Roll_std',
  'Tutorial_Yaw_range',
  'Tutorial_Pitch_range',
  'Tutorial_Roll_range',
  'Tutorial_mean_head_speed_in_orientation',
  'Tutorial_max_head_speed_in_orientation',
  'Tutorial_std_head_speed_in_orientation',
  'Tutorial_gaze_obj_looked_ratio',
  'Tutorial_gaze_switch_count',
  'Tutorial_dominant_hand_total_distance',
  'Tutorial_not_dominant_hand_total_distance',
  'Tutorial_dominant_hand_mean_speed',
  'Tutorial_not_dominant_hand_mean_speed',
  'Tutorial_dominant_hand_max_speed',
  'Tutorial_not_dominant_hand_max_speed',
  'Tutorial_dominant_hand_x_range',
  'Tutorial_dominant_hand_y_range',
  'Tutorial_dominant_hand_z_range',
  'Tutorial_not_dominant_hand_x_range',
  'Tutorial_not_dominant_hand_y_range',
  'Tutorial_not_dominant_hand_z_range',
  'Tutorial_dominant_hand_trigger_press_count',
  'Tutorial_not_dominant_hand_trigger_press_count',
  'Tutorial_dominant_hand_trigger_pressure_mean',
  'Tutorial_not_dominant_hand_trigger_pressure_mean',
  'Tutorial_dominant_hand_grip_count',
  'Tutorial_not_dominant_hand_grip_count',
  'Tutorial_dominant_hand_grip_mean',
  'Tutorial_not_dominant_hand_grip_mean'],
 ['ObjectRecognition_total_reading_time',
  'ObjectRecognition_mean_reading_time',
  'ObjectRecognition_max_reading_time',
  'ObjectRecognition_median_reading_time',
  'ObjectRecognition_std_reading_time',
  'ObjectRecognition_intensity_reading_time',
  'ObjectRecognition_total_count_hover',
  'ObjectRecognition_total_duration_hover',
  'ObjectRecognition_mean_duration_hover',
  'ObjectRecognition_max_duration_hover',
  'ObjectRecognition_median_duration_hover',
  'ObjectRecognition_std_duration_hover',
  'ObjectRecognition_intensity_hover',
  'ObjectRecognition_total_count_press',
  'ObjectRecognition_total_duration_press',
  'ObjectRecognition_mean_duration_press',
  'ObjectRecognition_max_duration_press',
  'ObjectRecognition_median_duration_press',
  'ObjectRecognition_std_duration_press',
  'ObjectRecognition_intensity_press',
  'ObjectRecognition_total_count_grab',
  'ObjectRecognition_total_duration_grab',
  'ObjectRecognition_mean_duration_grab',
  'ObjectRecognition_max_duration_grab',
  'ObjectRecognition_median_duration_grab',
  'ObjectRecognition_std_duration_grab',
  'ObjectRecognition_intensity_grab',
  'ObjectRecognition_total_count_gaze',
  'ObjectRecognition_total_duration_gaze',
  'ObjectRecognition_mean_duration_gaze',
  'ObjectRecognition_max_duration_gaze',
  'ObjectRecognition_median_duration_gaze',
  'ObjectRecognition_std_duration_gaze',
  'ObjectRecognition_intensity_gaze',
  'ObjectRecognition_hover_vs_reading_time_ratio',
  'ObjectRecognition_hover_vs_active_interaction_ratio',
  'ObjectRecognition_interaction_fraction',
  'ObjectRecognition_decision_latency',
  'ObjectRecognition_clicks_per_second',
  'ObjectRecognition_hovers_per_click',
  'ObjectRecognition_time_before_first_press',
  'ObjectRecognition_time_before_first_hover',
  'ObjectRecognition_score',
  'ObjectRecognition_mean_success_duration',
  'ObjectRecognition_mean_choose_wrong_obj',
  'ObjectRecognition_total_duration',
  'ObjectRecognition_head_total_distance',
  'ObjectRecognition_HMD_X_std',
  'ObjectRecognition_HMD_Y_std',
  'ObjectRecognition_HMD_Z_std',
  'ObjectRecognition_HMD_X_range',
  'ObjectRecognition_HMD_Y_range',
  'ObjectRecognition_HMD_Z_range',
  'ObjectRecognition_mean_head_speed_in_distance',
  'ObjectRecognition_max_head_speed_in_distance',
  'ObjectRecognition_std_head_speed_in_distance',
  'ObjectRecognition_head_total_orientation',
  'ObjectRecognition_Yaw_std',
  'ObjectRecognition_Pitch_std',
  'ObjectRecognition_Roll_std',
  'ObjectRecognition_Yaw_range',
  'ObjectRecognition_Pitch_range',
  'ObjectRecognition_Roll_range',
  'ObjectRecognition_mean_head_speed_in_orientation',
  'ObjectRecognition_max_head_speed_in_orientation',
  'ObjectRecognition_std_head_speed_in_orientation',
  'ObjectRecognition_gaze_obj_looked_ratio',
  'ObjectRecognition_gaze_switch_count',
  'ObjectRecognition_dominant_hand_total_distance',
  'ObjectRecognition_not_dominant_hand_total_distance',
  'ObjectRecognition_dominant_hand_mean_speed',
  'ObjectRecognition_not_dominant_hand_mean_speed',
  'ObjectRecognition_dominant_hand_max_speed',
  'ObjectRecognition_not_dominant_hand_max_speed',
  'ObjectRecognition_dominant_hand_x_range',
  'ObjectRecognition_dominant_hand_y_range',
  'ObjectRecognition_dominant_hand_z_range',
  'ObjectRecognition_not_dominant_hand_x_range',
  'ObjectRecognition_not_dominant_hand_y_range',
  'ObjectRecognition_not_dominant_hand_z_range',
  'ObjectRecognition_dominant_hand_trigger_press_count',
  'ObjectRecognition_not_dominant_hand_trigger_press_count',
  'ObjectRecognition_dominant_hand_trigger_pressure_mean',
  'ObjectRecognition_not_dominant_hand_trigger_pressure_mean',
  'ObjectRecognition_dominant_hand_grip_count',
  'ObjectRecognition_not_dominant_hand_grip_count',
  'ObjectRecognition_dominant_hand_grip_mean',
  'ObjectRecognition_not_dominant_hand_grip_mean'],
 ['Visuospatial_total_reading_time',
  'Visuospatial_mean_reading_time',
  'Visuospatial_max_reading_time',
  'Visuospatial_median_reading_time',
  'Visuospatial_std_reading_time',
  'Visuospatial_intensity_reading_time',
  'Visuospatial_total_count_hover',
  'Visuospatial_total_duration_hover',
  'Visuospatial_mean_duration_hover',
  'Visuospatial_max_duration_hover',
  'Visuospatial_median_duration_hover',
  'Visuospatial_std_duration_hover',
  'Visuospatial_intensity_hover',
  'Visuospatial_total_count_press',
  'Visuospatial_total_duration_press',
  'Visuospatial_mean_duration_press',
  'Visuospatial_max_duration_press',
  'Visuospatial_median_duration_press',
  'Visuospatial_std_duration_press',
  'Visuospatial_intensity_press',
  'Visuospatial_total_count_grab',
  'Visuospatial_total_duration_grab',
  'Visuospatial_mean_duration_grab',
  'Visuospatial_max_duration_grab',
  'Visuospatial_median_duration_grab',
  'Visuospatial_std_duration_grab',
  'Visuospatial_intensity_grab',
  'Visuospatial_total_count_gaze',
  'Visuospatial_total_duration_gaze',
  'Visuospatial_mean_duration_gaze',
  'Visuospatial_max_duration_gaze',
  'Visuospatial_median_duration_gaze',
  'Visuospatial_std_duration_gaze',
  'Visuospatial_intensity_gaze',
  'Visuospatial_hover_vs_reading_time_ratio',
  'Visuospatial_hover_vs_active_interaction_ratio',
  'Visuospatial_interaction_fraction',
  'Visuospatial_decision_latency',
  'Visuospatial_clicks_per_second',
  'Visuospatial_hovers_per_click',
  'Visuospatial_time_before_first_press',
  'Visuospatial_time_before_first_hover',
  'Visuospatial_score',
  'Visuospatial_total_wrong_placement',
  'Visuospatial_total_duration',
  'Visuospatial_head_total_distance',
  'Visuospatial_HMD_X_std',
  'Visuospatial_HMD_Y_std',
  'Visuospatial_HMD_Z_std',
  'Visuospatial_HMD_X_range',
  'Visuospatial_HMD_Y_range',
  'Visuospatial_HMD_Z_range',
  'Visuospatial_mean_head_speed_in_distance',
  'Visuospatial_max_head_speed_in_distance',
  'Visuospatial_std_head_speed_in_distance',
  'Visuospatial_head_total_orientation',
  'Visuospatial_Yaw_std',
  'Visuospatial_Pitch_std',
  'Visuospatial_Roll_std',
  'Visuospatial_Yaw_range',
  'Visuospatial_Pitch_range',
  'Visuospatial_Roll_range',
  'Visuospatial_mean_head_speed_in_orientation',
  'Visuospatial_max_head_speed_in_orientation',
  'Visuospatial_std_head_speed_in_orientation',
  'Visuospatial_gaze_obj_looked_ratio',
  'Visuospatial_gaze_switch_count',
  'Visuospatial_dominant_hand_total_distance',
  'Visuospatial_not_dominant_hand_total_distance',
  'Visuospatial_dominant_hand_mean_speed',
  'Visuospatial_not_dominant_hand_mean_speed',
  'Visuospatial_dominant_hand_max_speed',
  'Visuospatial_not_dominant_hand_max_speed',
  'Visuospatial_dominant_hand_x_range',
  'Visuospatial_dominant_hand_y_range',
  'Visuospatial_dominant_hand_z_range',
  'Visuospatial_not_dominant_hand_x_range',
  'Visuospatial_not_dominant_hand_y_range',
  'Visuospatial_not_dominant_hand_z_range',
  'Visuospatial_dominant_hand_trigger_press_count',
  'Visuospatial_not_dominant_hand_trigger_press_count',
  'Visuospatial_dominant_hand_trigger_pressure_mean',
  'Visuospatial_not_dominant_hand_trigger_pressure_mean',
  'Visuospatial_dominant_hand_grip_count',
  'Visuospatial_not_dominant_hand_grip_count',
  'Visuospatial_dominant_hand_grip_mean',
  'Visuospatial_not_dominant_hand_grip_mean'],
 ['Memory_total_reading_time',
  'Memory_mean_reading_time',
  'Memory_max_reading_time',
  'Memory_median_reading_time',
  'Memory_std_reading_time',
  'Memory_intensity_reading_time',
  'Memory_total_count_hover',
  'Memory_total_duration_hover',
  'Memory_mean_duration_hover',
  'Memory_max_duration_hover',
  'Memory_median_duration_hover',
  'Memory_std_duration_hover',
  'Memory_intensity_hover',
  'Memory_total_count_press',
  'Memory_total_duration_press',
  'Memory_mean_duration_press',
  'Memory_max_duration_press',
  'Memory_median_duration_press',
  'Memory_std_duration_press',
  'Memory_intensity_press',
  'Memory_total_count_grab',
  'Memory_total_duration_grab',
  'Memory_mean_duration_grab',
  'Memory_max_duration_grab',
  'Memory_median_duration_grab',
  'Memory_std_duration_grab',
  'Memory_intensity_grab',
  'Memory_total_count_gaze',
  'Memory_total_duration_gaze',
  'Memory_mean_duration_gaze',
  'Memory_max_duration_gaze',
  'Memory_median_duration_gaze',
  'Memory_std_duration_gaze',
  'Memory_intensity_gaze',
  'Memory_hover_vs_reading_time_ratio',
  'Memory_hover_vs_active_interaction_ratio',
  'Memory_interaction_fraction',
  'Memory_decision_latency',
  'Memory_clicks_per_second',
  'Memory_hovers_per_click',
  'Memory_time_before_first_press',
  'Memory_time_before_first_hover',
  'Memory_score',
  'Memory_delay_first_action',
  'Memory_total_wrong_recall',
  'Memory_mean_recall',
  'Memory_cognitive_freez_count',
  'Memory_cognitive_freez_mean_duration',
  'Memory_total_duration',
  'Memory_head_total_distance',
  'Memory_HMD_X_std',
  'Memory_HMD_Y_std',
  'Memory_HMD_Z_std',
  'Memory_HMD_X_range',
  'Memory_HMD_Y_range',
  'Memory_HMD_Z_range',
  'Memory_mean_head_speed_in_distance',
  'Memory_max_head_speed_in_distance',
  'Memory_std_head_speed_in_distance',
  'Memory_head_total_orientation',
  'Memory_Yaw_std',
  'Memory_Pitch_std',
  'Memory_Roll_std',
  'Memory_Yaw_range',
  'Memory_Pitch_range',
  'Memory_Roll_range',
  'Memory_mean_head_speed_in_orientation',
  'Memory_max_head_speed_in_orientation',
  'Memory_std_head_speed_in_orientation',
  'Memory_gaze_obj_looked_ratio',
  'Memory_gaze_switch_count',
  'Memory_dominant_hand_total_distance',
  'Memory_not_dominant_hand_total_distance',
  'Memory_dominant_hand_mean_speed',
  'Memory_not_dominant_hand_mean_speed',
  'Memory_dominant_hand_max_speed',
  'Memory_not_dominant_hand_max_speed',
  'Memory_dominant_hand_x_range',
  'Memory_dominant_hand_y_range',
  'Memory_dominant_hand_z_range',
  'Memory_not_dominant_hand_x_range',
  'Memory_not_dominant_hand_y_range',
  'Memory_not_dominant_hand_z_range',
  'Memory_dominant_hand_trigger_press_count',
  'Memory_not_dominant_hand_trigger_press_count',
  'Memory_dominant_hand_trigger_pressure_mean',
  'Memory_not_dominant_hand_trigger_pressure_mean',
  'Memory_dominant_hand_grip_count',
  'Memory_not_dominant_hand_grip_count',
  'Memory_dominant_hand_grip_mean',
  'Memory_not_dominant_hand_grip_mean']]

# 3. Creating df

In [65]:
def create_df():
    columns = [col for lst in all_phase_column_lists for col in lst]
    extracted_features_df = pd.DataFrame(columns=columns)
    return extracted_features_df

extracted_features_df = create_df()
extracted_features_df.columns

Index(['Paitent_id', 'Age', 'Gender', 'dominant_hand',
       'Sessions_Completed_out_of_4', 'Help_Rating_out_of_5',
       'Tutorial_total_reading_time', 'Tutorial_mean_reading_time',
       'Tutorial_max_reading_time', 'Tutorial_median_reading_time',
       ...
       'Memory_not_dominant_hand_y_range', 'Memory_not_dominant_hand_z_range',
       'Memory_dominant_hand_trigger_press_count',
       'Memory_not_dominant_hand_trigger_press_count',
       'Memory_dominant_hand_trigger_pressure_mean',
       'Memory_not_dominant_hand_trigger_pressure_mean',
       'Memory_dominant_hand_grip_count',
       'Memory_not_dominant_hand_grip_count', 'Memory_dominant_hand_grip_mean',
       'Memory_not_dominant_hand_grip_mean'],
      dtype='str', length=356)

# 4. Filling the extracted_features_df

In [72]:

df_event[df_event['EventType'].isin(['GRAB_RELEASE'])]

Empty DataFrame
Columns: [Timestamp, PhaseTime_s, Section, EventType, ObjectName, Hand, IsCorrect, Duration_s, Distance_m, Details, Activity_Log]
Index: []

In [74]:
if len(extracted_features_df)!= 0:
    extracted_features_df = create_df()


print("STARTING....")
# First loop
for patient_id in patient_ids:
    
    print("============================================================")
    # First loop : fill patient data
    print(f"Extracting row for patient : {patient_id}")
    
    # extract data path
    patient_folder_path = du.find_patient_folder(patients_data_folder=patients_data_folder,
                                                 patient_id=patient_id)
    row_index = patient_ids.index(patient_id)

    # filling patient dictionary
    patient_dict = du.filling_patient_dict(patients_data_log_df, patient_dict, row_index)
    
    # filling phase dictionaries
    path_to_check  = patient_folder_path / "clean_data"
    unsorted_csv_files_list = du.find_csv_file(patient_folder_path / "clean_data")
    csv_files_list = sorted(unsorted_csv_files_list, key=du.get_order) # sort the filenames in correct order
    
    # set dominant and not dominant hand
    dominant_hand = patient_dict["dominant_hand"]
    not_dominant_hand = 'Left' if dominant_hand == 'Right' else 'Right'

    print("Patient infos extracted successfully.")

    # phase id (range 1 to 4)
    phase_id = 1
    all_four_phase_dict = []

    # Second loop: now fill 4 phases (event+trajectory)
    for i in range(0,8,2):
        
        # Event file
        csv_file_event = csv_files_list[i]
        df_event       = pd.read_csv(path_to_check / csv_file_event)
        
        # extract phase duration
        phase_duration = du.extract_phase_duration(df_event)

        # extract phase name
        match      = re.search(r'_([^_]+)_events\.csv$', csv_file_event)
        phase_name =  match.group(1) if match else sys.exit("phase name not found!!!")

        # filling
        phase_name = phase_name if phase_name in phase_name_list else gf.fail(msg="phase_name is found but it's invalid!!!", error="Key not found")

        print(f"starting the new phase: {phase_name}")

        # filling for events
        #event_dict = dp.creating_event_dictionary(df_event, phase_name , event_empty_dictionaries, extra_features_empty_dictionaries, phase_duration)
        
        print(df_event[df_event['EventType'].isin(['GRAB_RELEASE'])]['Duration_s'])
        # Trajectory file
        csv_file_trajectory = csv_files_list[i+1]
        df_trajectory       = pd.read_csv(path_to_check / csv_file_trajectory)

        # filling for trajectory
        #trajectory_dict = dp.creating_trajectory_dictionary(df_trajectory, dominant_hand, not_dominant_hand, trajectory_empty_dictionaries)
        continue
        # prepareing event_dict and trajectory_dict columns for assgining (with extra feautres, depends on phase_name)
        if  phase_name == phase_name_list[0]: # Tutorial
            # add prefix tutorial_ to all keys
            event_dict      = {f"Tutorial_{k}": v for k, v in event_dict.items()}
            trajectory_dict = {f"Tutorial_{k}": v for k, v in trajectory_dict.items()}

        elif phase_name == phase_name_list[1]: # ObjectRecognition
            
            # extract list of extra features(they already have the prefix!)
            extra_features_keys = list(extra_features_empty_dictionaries[0].keys())

            # add prefix objectrecognition_ to all keys
            event_dict = {
                (f"ObjectRecognition_{k}" if k not in extra_features_keys else k): v
                for k, v in event_dict.items()
            }

            trajectory_dict = {f"ObjectRecognition_{k}": v for k, v in trajectory_dict.items()}
            
        elif phase_name == phase_name_list[2]: # Visuospatial
            
            # extract list of extra features(they already have the prefix!)
            extra_features_keys = list(extra_features_empty_dictionaries[1].keys())

            # add prefix visuospatial_ to all keys
            event_dict = {
                (f"Visuospatial_{k}" if k not in extra_features_keys else k): v
                for k, v in event_dict.items()
            }

            trajectory_dict = {f"Visuospatial_{k}": v for k, v in trajectory_dict.items()}

        elif phase_name == phase_name_list[3]: # Memory
            
            # extract list of extra features(they already have the prefix!)
            extra_features_keys = list(extra_features_empty_dictionaries[2].keys())

            # add prefix memory_ to all keys
            event_dict = {
                (f"Memory_{k}" if k not in extra_features_keys else k): v
                for k, v in event_dict.items()
            }

            trajectory_dict = {f"Memory_{k}": v for k, v in trajectory_dict.items()}
        
        concated_phase_dict = event_dict | trajectory_dict
        all_four_phase_dict.append(concated_phase_dict)
        
        print(f"Features extracted successfully.")

    print("All four phases are done.")
    print(all_four_phase_dict[0])
    # concate phase dictionary and patient
    single_row_of_df = patient_dict | all_four_phase_dict[0] | all_four_phase_dict[1] | all_four_phase_dict[2] | all_four_phase_dict[3]

    # add single row to final dataframe
    extracted_features_df.loc[len(extracted_features_df)] = single_row_of_df
    print("New row added to df successfully.")
    
    print("============================================================")

print("Main process is finished.")

STARTING....
============================================================
Extracting row for patient : P001
Patient infos extracted successfully.
starting the new phase: Tutorial
48    1.485
52    1.125
61    1.486
68    1.487
Name: Duration_s, dtype: float64
starting the new phase: ObjectRecognition
Series([], Name: Duration_s, dtype: float64)
starting the new phase: Visuospatial
44     7.334
54     2.140
64     1.931
73     1.514
82     2.430
96     1.833
105    1.555
Name: Duration_s, dtype: float64
starting the new phase: Memory
60     12.142
78      7.195
97      8.168
124     4.333
147     2.653
163     1.292
184     4.764
234    17.695
244     1.444
317     3.569
331     1.166
355     7.876
489    21.347
519     1.639
528     0.849
595    19.514
606     1.471
624    14.654
644     2.140
666     1.417
706     3.515
Name: Duration_s, dtype: float64
All four phases are done.

IndexError: list index out of range

In [ ]:
extracted_features_df

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,Tutorial_total_reading_time,Tutorial_mean_reading_time,Tutorial_max_reading_time,Tutorial_median_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,P001,None,Female,Right,4,1,45.03,15.01,21.00,17.23,...,0.80,0.50,35,0,0.01,0.00,1275,0,0.40,0.0
1,P002,59,Female,Right,4,3,171.99,57.33,91.56,69.81,...,0.61,1.15,63,0,0.02,0.00,222,0,0.09,0.0
2,P003,82,Male,Right,4,4,338.75,112.92,155.14,147.97,...,0.75,0.61,12,0,0.00,0.00,277,0,0.09,0.0
3,P004,75,Male,Left,4,3,114.78,38.26,68.19,43.00,...,0.59,0.92,47,1,0.03,0.00,157,0,0.10,0.0
4,P005,62,Male,Right,4,4,152.90,50.97,88.47,42.24,...,0.58,0.48,28,0,0.02,0.00,125,0,0.08,0.0
5,P006,78,Female,Right,4,3,181.69,60.56,90.17,75.06,...,0.42,0.71,244,0,0.12,0.00,261,0,0.13,0.0
6,P007,71,Female,Right,4,3,190.51,63.50,83.86,57.69,...,0.64,0.46,12,0,0.01,0.00,159,0,0.11,0.0
7,P008,69,Female,Right,4,4,208.51,69.50,99.78,67.13,...,0.33,0.92,27,0,0.02,0.00,127,0,0.08,0.0
8,P009,73,Male,Right,4,2,198.53,66.18,94.27,90.08,...,0.59,0.72,631,0,0.23,0.00,630,0,0.21,0.0
9,P010,81,Female,Right,4,3,265.83,88.61,115.47,95.42,...,0.63,0.69,284,0,0.18,0.00,799,0,0.21,0.0
10,P011,74,Female,Right,4,3,210.34,70.11,79.48,70.82,...,0.33,0.22,12,0,0.01,0.00,159,0,0.14,0.0
11,P012,65,Male,Right,4,3,164.28,54.76,60.26,58.93,...,0.46,0.38,8,0,0.01,0.00,112,0,0.10,0.0
12,P013,61,Female,Right,4,3,109.99,36.66,62.12,31.25,...,0.41,0.19,14,0,0.01,0.00,136,0,0.13,0.0
13,P014,79,Male,Left,4,1,534.07,178.02,206.77,197.68,...,0.79,0.66,1457,2,0.40,0.00,1545,11,0.44,0.0
14,P015,74,Female,Right,4,3,269.98,89.99,180.21,66.22,...,0.38,0.70,46,0,0.04,0.00,173,0,0.15,0.0
15,P016,75,Female,Right,4,3,260.47,86.82,122.55,121.28,...,0.47,0.69,65,0,0.03,0.00,136,0,0.11,0.0
16,P017,76,Female,Right,4,3,241.54,80.51,184.65,45.79,...,0.49,0.70,10,0,0.01,0.00,233,0,0.18,0.0
17,P018,69,Female,Right,4,3,371.73,123.91,194.47,137.26,...,0.70,0.76,58,116,0.03,0.01,171,4,0.13,0.0
18,P019,70,Male,Right,4,3,279.39,93.13,178.58,88.00,...,0.54,0.79,284,0,0.20,0.00,273,0,0.20,0.0
19,P020,72,Female,Right,4,3,201.54,67.18,95.63,87.69,...,0.41,0.26,57,0,0.03,0.00,250,0,0.18,0.0

# 5. Save df

In [45]:
path_df = data_folder / "produced_csv"
name = '1.extracted_features.csv'
extracted_features_df.to_csv(path_df / name, index=False)

In [46]:
extracted_features_df.head()

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,Tutorial_total_reading_time,Tutorial_mean_reading_time,Tutorial_max_reading_time,Tutorial_median_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,P001,None,Female,Right,4,1,45.03,15.01,21.00,17.23,...,0.80,0.50,35,0,0.01,0.0,1275,0,0.40,0.0
1,P002,59,Female,Right,4,3,171.99,57.33,91.56,69.81,...,0.61,1.15,63,0,0.02,0.0,222,0,0.09,0.0
2,P003,82,Male,Right,4,4,338.75,112.92,155.14,147.97,...,0.75,0.61,12,0,0.00,0.0,277,0,0.09,0.0
3,P004,75,Male,Left,4,3,114.78,38.26,68.19,43.00,...,0.59,0.92,47,1,0.03,0.0,157,0,0.10,0.0
4,P005,62,Male,Right,4,4,152.90,50.97,88.47,42.24,...,0.58,0.48,28,0,0.02,0.0,125,0,0.08,0.0

In [ ]:
'Visuospatial_head_total_distance'

In [58]:
print(all_four_phase_dict[1])

{'ObjectRecognition_total_reading_time': np.float64(9.01), 'ObjectRecognition_mean_reading_time': np.float64(3.0), 'ObjectRecognition_max_reading_time': np.float64(3.01), 'ObjectRecognition_median_reading_time': np.float64(3.0), 'ObjectRecognition_std_reading_time': np.float64(0.01), 'ObjectRecognition_intensity_reading_time': np.float64(0.11), 'ObjectRecognition_total_count_hover': 16, 'ObjectRecognition_total_duration_hover': np.float64(30.83), 'ObjectRecognition_mean_duration_hover': np.float64(7.54), 'ObjectRecognition_max_duration_hover': np.float64(2.2), 'ObjectRecognition_median_duration_hover': np.float64(1.73), 'ObjectRecognition_std_duration_hover': np.float64(2.1), 'ObjectRecognition_intensity_hover': np.float64(0.39), 'ObjectRecognition_total_count_press': 4, 'ObjectRecognition_total_duration_press': np.float64(1.6), 'ObjectRecognition_mean_duration_press': np.float64(0.97), 'ObjectRecognition_max_duration_press': np.float64(0.8), 'ObjectRecognition_median_duration_press': np.float64(0.8), 'ObjectRecognition_std_duration_press': np.float64(0.25), 'ObjectRecognition_intensity_press': np.float64(0.02), 'ObjectRecognition_total_count_grab': 0, 'ObjectRecognition_total_duration_grab': np.float64(0.0), 'ObjectRecognition_mean_duration_grab': nan, 'ObjectRecognition_max_duration_grab': nan, 'ObjectRecognition_median_duration_grab': nan, 'ObjectRecognition_std_duration_grab': nan, 'ObjectRecognition_intensity_grab': np.float64(0.0), 'ObjectRecognition_total_count_gaze': 1, 'ObjectRecognition_total_duration_gaze': np.float64(0.12), 'ObjectRecognition_mean_duration_gaze': np.float64(0.12), 'ObjectRecognition_max_duration_gaze': np.float64(0.12), 'ObjectRecognition_median_duration_gaze': np.float64(0.12), 'ObjectRecognition_std_duration_gaze': np.float64(nan), 'ObjectRecognition_intensity_gaze': np.float64(0.0), 'ObjectRecognition_hover_vs_reading_time_ratio': np.float64(3.42), 'ObjectRecognition_hover_vs_active_interaction_ratio': np.float64(19.27), 'ObjectRecognition_interaction_fraction': np.float64(0.41), 'ObjectRecognition_decision_latency': np.float64(16.33), 'ObjectRecognition_clicks_per_second': np.float64(0.05), 'ObjectRecognition_hovers_per_click': 4.0, 'ObjectRecognition_time_before_first_press': np.float64(28.225), 'ObjectRecognition_time_before_first_hover': np.float64(11.893), 'ObjectRecognition_score': 1.0, 'ObjectRecognition_mean_success_duration': np.float64(5.26), 'ObjectRecognition_mean_choose_wrong_obj': np.float64(0.67), 'ObjectRecognition_total_duration': np.float64(32.289), 'ObjectRecognition_head_total_distance': np.float64(0.98), 'ObjectRecognition_HMD_X_std': np.float64(0.02), 'ObjectRecognition_HMD_Y_std': np.float64(0.02), 'ObjectRecognition_HMD_Z_std': np.float64(0.01), 'ObjectRecognition_HMD_X_range': np.float64(0.08), 'ObjectRecognition_HMD_Y_range': np.float64(0.11), 'ObjectRecognition_HMD_Z_range': np.float64(0.06), 'ObjectRecognition_mean_head_speed_in_distance': np.float64(0.01), 'ObjectRecognition_max_head_speed_in_distance': np.float64(0.47), 'ObjectRecognition_std_head_speed_in_distance': np.float64(0.04), 'ObjectRecognition_head_total_orientation': np.float64(11870.47), 'ObjectRecognition_Yaw_std': np.float64(11.54), 'ObjectRecognition_Pitch_std': np.float64(159.02), 'ObjectRecognition_Roll_std': np.float64(124.21), 'ObjectRecognition_Yaw_range': np.float64(60.26), 'ObjectRecognition_Pitch_range': np.float64(359.84), 'ObjectRecognition_Roll_range': np.float64(359.97), 'ObjectRecognition_mean_head_speed_in_orientation': np.float64(149.5), 'ObjectRecognition_max_head_speed_in_orientation': np.float64(3302.48), 'ObjectRecognition_std_head_speed_in_orientation': np.float64(654.2), 'ObjectRecognition_gaze_obj_looked_ratio': np.float64(0.0), 'ObjectRecognition_gaze_switch_count': 0, 'ObjectRecognition_dominant_hand_total_distance': np.float64(1.66), 'ObjectRecognition_not_dominant_hand_total_distance': np.float64(0.05), 'ObjectRecognition_dominant_hand_mean_speed': np.float64(0.02), 'ObjectRecognition_dominant_hand_max_speed': np.float64(0.47), 'ObjectRecognition_not_dominant_hand_mean_speed': np.float64(0.0), 'ObjectRecognition_not_dominant_hand_max_speed': np.float64(0.47), 'ObjectRecognition_dominant_hand_x_range': np.float64(0.16), 'ObjectRecognition_dominant_hand_y_range': np.float64(0.19), 'ObjectRecognition_dominant_hand_z_range': np.float64(0.22), 'ObjectRecognition_not_dominant_hand_x_range': np.float64(0.0), 'ObjectRecognition_not_dominant_hand_y_range': np.float64(0.05), 'ObjectRecognition_not_dominant_hand_z_range': np.float64(0.0), 'ObjectRecognition_dominant_hand_trigger_press_count': 50, 'ObjectRecognition_dominant_hand_trigger_pressure_mean': np.float64(0.06), 'ObjectRecognition_not_dominant_hand_trigger_press_count': 0, 'ObjectRecognition_not_dominant_hand_trigger_pressure_mean': np.float64(0.0), 'ObjectRecognition_dominant_hand_grip_count': 69, 'ObjectRecognition_dominant_hand_grip_mean': np.float64(0.08), 'ObjectRecognition_not_dominant_hand_grip_count': 0, 'ObjectRecognition_not_dominant_hand_grip_mean': np.float64(0.0)}

In [57]:
col_with_Nan_values = extracted_features_df.isna().sum()[extracted_features_df.isna().sum() > 5].to_dict()
col_with_Nan_values

{'ObjectRecognition_mean_duration_grab': 20,
 'ObjectRecognition_max_duration_grab': 20,
 'ObjectRecognition_median_duration_grab': 20,
 'ObjectRecognition_std_duration_grab': 20,
 'ObjectRecognition_mean_duration_gaze': 8,
 'ObjectRecognition_max_duration_gaze': 8,
 'ObjectRecognition_median_duration_gaze': 8,
 'ObjectRecognition_std_duration_gaze': 14,
 'Memory_cognitive_freez_mean_duration': 17}

In [48]:
extracted_features_df.columns

Index(['Paitent_id', 'Age', 'Gender', 'dominant_hand',
       'Sessions_Completed_out_of_4', 'Help_Rating_out_of_5',
       'Tutorial_total_reading_time', 'Tutorial_mean_reading_time',
       'Tutorial_max_reading_time', 'Tutorial_median_reading_time',
       ...
       'Memory_not_dominant_hand_y_range', 'Memory_not_dominant_hand_z_range',
       'Memory_dominant_hand_trigger_press_count',
       'Memory_not_dominant_hand_trigger_press_count',
       'Memory_dominant_hand_trigger_pressure_mean',
       'Memory_not_dominant_hand_trigger_pressure_mean',
       'Memory_dominant_hand_grip_count',
       'Memory_not_dominant_hand_grip_count', 'Memory_dominant_hand_grip_mean',
       'Memory_not_dominant_hand_grip_mean'],
      dtype='str', length=356)