# 0.Library

In [83]:
import pandas as pd
from pathlib import Path

import importlib
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp

# Reload
importlib.reload(du)
importlib.reload(dp)

# Constants and paths
parent_folder = Path("../..") # go 2 folder up= "../.."
data_folder = parent_folder / "data"
input_path_of_json = data_folder / "patients_data_log.json"
df_data_log = pd.read_json(input_path_of_json)

patient_ids = df_data_log["PatientID"].to_list()
patients_data_folder = data_folder / "PatientsData"

# 1. Phase-Level Feature vectors structure
same as in Readme.md

In [2]:
features_dict = {
    "phase_id": None,
    "phase_name": None,
    "phase_duration": None,
}

## 1.1 Events file

In [3]:
# statistical features
reading_time_dict = {
    "total": None,
    "mean": None,
    "max": None,
    "median": None,
    "std": None,
    "intensity" : None
}

hover_dict = {
    "total_hover_count": None,
    "total_hover_duration": None,
    "mean_hover_duration": None,
    "max_hover_duration": None,
    "median_hover_duration": None,
    "std_hover_duration": None,
    "cv_hover_duration": None, # std_hover_duration / mean_hover_duration
    "hover_intensity": None
}

press_dict = {
    "total_press_count": None,
    "total_press_duration": None,
    "mean_press_duration": None,
    "max_press_duration": None,
    "median_press_duration": None,
    "std_press_duration": None,
    "press_intensity": None # Interaction intensity
}

grab_dict = {
    "total_grab_count": None,
    "total_grab_duration": None,
    "mean_grab_duration": None,
    "max_grab_duration": None,
    "median_grab_duration": None,
    "std_grab_duration": None,
    "grab_intensity": None # Interaction intensity
}

gaze_dict = {
    "total_gaze_count": None,
    "total_gaze_duration": None,
    "mean_gaze_duration": None,
    "max_gaze_duration": None,
    "median_gaze_duration": None,
    "std_gaze_duration": None,
    "gaze_intensity": None # Interaction intensity
}

# Behavioral features
behavior_dict = {
    "hover_vs_reading_time_ratio": None,
    "hover_vs_active_interaction_ratio": None,
    "interaction_fraction": None,
    "decision_latency": None,  
    "clicks_per_second": None,
    "hovers_per_click": None
}

# Temporal Features
temporal_dict = {
    "time_before_first_press": None,
    "time_before_first_hover": None
}

## 1.2 Trajectory file

In [4]:
# Head features
headset_dict = {
    # Position features
    "head_total_distance": None,

    "HMD_X_std": None,
    "HMD_Y_std": None,
    "HMD_Z_std": None,

    "HMD_X_range": None,
    "HMD_Y_range": None,
    "HMD_Z_range": None,

    # Speed features
    "mean_head_speed": None,
    "max_head_speed": None,
    "std_head_speed": None,

    # Orientation features
    "Yaw_std": None,
    "Pitch_std": None,
    "Roll_std": None,
    "Yaw_range": None,
    "Pitch_range": None,
    "Roll_range": None,

    # Exploration features
    "exploration_index": None,

    # Gaze features
    "gaze_target_counts": None,
    "gaze_switch_count": None

}

# Hand features
controller_dict = {
    # Distance features
    "dominant_hand_total_distance": None,
    "not_dominant_hand_total_distance": None,

    # Speed features
    "dominant_hand_mean_speed": None,
    "not_dominant_hand_mean_speed": None,
    "dominant_hand_max_speed": None,
    "not_dominant_hand_max_speed": None,

    # Workspace_volume features
    "dominant_hand_x_range": None,
    "dominant_hand_y_range": None,
    "dominant_hand_z_range": None,
    "not_dominant_hand_x_range": None,
    "not_dominant_hand_y_range": None,
    "not_dominant_hand_z_range": None,

    # Active time features
    "dominant_hand_trigger_active_time": None,
    "not_dominant_hand_trigger_active_time": None,

    # Press count features
    "dominant_hand_trigger_press_count": None,
    "not_dominant_hand_trigger_press_count": None,

    # Grab count features
    "dominant_hand_grab_count": None,
    "not_dominant_hand_grab_count": None,

    # Grib duration features
    "dominant_hand_grab_duration": None,
    "not_dominant_hand_grab_duration": None,

    # Symmetry feature
    "hand_movement_symmetry": None
}

# 2. Paitent-Level Feature vectors structure
same as in Readme.md

In [5]:
global_feature_dict = {
    "object_recognition_accuracy":None,
    "recognition_response_time_mean":None,
    "recognition_response_time_per_round":None,
    "visuospatial_placements_correct":None,
    "socket_rejection_count":None,
    "memory_recall_accuracy":None,
    "mean_recall_latency":None,
    "mean_placement_error_distance":None,
    "carry_time_per_object":None,
    "pickup_count_per_object":None,
    "cognitive_freeze_count":None,
    "cognitive_freeze_duration":None,
    "re-grab_delay_after_rejection":None,
    "gazed_correct_socket_after_rejection":None,
    "hover_count_before_grab":None,
    "recall_first_action_delay":None,
    "hand_path_length":None,
    "hand_speed_mean":None,
    "hand_speed_peak":None,
    "hand_jitter":None,
    "head_path_length":None,
    "total_yaw":None,
    "gaze_on_target_percentage":None,
    "gaze_switch_count":None,
}

# 3. Final dataframe

In [ ]:
paitent_dict = {
    "Paitent_id" : None,
    "Age" : None,
    "Gender" : None,
    "Sessions_Completed_out_of_4" : None,
    "Help_Rating_out_of_5" : None,
}

paitent_dict.update(features_dict)
paitent_dict.update(reading_time_dict)
paitent_dict.update(hover_dict)
paitent_dict.update(press_dict)
paitent_dict.update(grab_dict)
paitent_dict.update(gaze_dict)
paitent_dict.update(behavior_dict)
paitent_dict.update(temporal_dict)
paitent_dict.update(headset_dict)
paitent_dict.update(controller_dict)
paitent_dict.update(global_feature_dict)

In [8]:
df = pd.DataFrame(columns=paitent_dict.keys())
for i in range(10):
    new_row = pd.DataFrame([paitent_dict])
    df = pd.concat([df, new_row], ignore_index=True)
df

,Paitent_id,Age,Gender,Sessions_Completed_out_of_4,Help_Rating_out_of_5,phase_id,phase_name,phase_duration,total,mean,...,gazed_correct_socket_after_rejection,hover_count_before_grab,recall_first_action_delay,hand_path_length,hand_speed_mean,hand_speed_peak,hand_jitter,head_path_length,total_yaw,gaze_on_target_percentage
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

# 4. Fill out Dictionaries for one paitent

## 4.1 Get dataset paths

In [13]:
# get clean path of one patient (all csv files)
patient_id = patient_ids[0]
patient_folder_path = du.find_patient_folder(patients_data_folder=patients_data_folder,
                                               patient_id=patient_id)
                                               
path_to_check = patient_folder_path / "clean_data"
csv_files_list = du.find_csv_file(patient_folder_path / "clean_data")
csv_files_list

['cleaned_20260502_113117_01_Tutorial_events.csv',
 'cleaned_20260502_113117_01_Tutorial_trajectory.csv',
 'cleaned_20260502_113117_02_ObjectRecognition_events.csv',
 'cleaned_20260502_113117_02_ObjectRecognition_trajectory.csv',
 'cleaned_20260502_113117_03_Visuospatial_events.csv',
 'cleaned_20260502_113117_03_Visuospatial_trajectory.csv',
 'cleaned_20260502_113117_04_Memory_events.csv',
 'cleaned_20260502_113117_04_Memory_trajectory.csv']

## 4.2 Phase-Level dictionary

### 4.2.1 Phase 0 : Tutorial phase_events

In [14]:
df = pd.read_csv(path_to_check / csv_files_list[0])
df.head()

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log
0,2026-05-02 11:31:17.628,0.000,Default,PHASE_START,NaN,NaN,NaN,0.0,0.0,Phase=01_Tutorial,"['Section=Default', 'SessionID=20260502_113117..."
1,2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,NaN,NaN,0.0,0.0,Section=Default,['Panel=WelcomePanel']
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
3,2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...

#### Fill out features_dict

In [20]:
features_dict["phase_id"] = 1
features_dict["phase_name"] = "toturial"
features_dict["phase_duration"] = du.extract_phase_duration(df)

features_dict

{'phase_id': 1, 'phase_name': 'toturial', 'phase_duration': np.float64(49.04)}

#### Fill out reading_time_dict

In [79]:
reading_time_series = df[df['EventType']=='PANEL_DISMISSED']['Activity_Log'].apply(du.extract_value_from_string,pattern_list=[r"ReadingTime=([0-9]*\.?[0-9]+)"], type_to_extract=float)

['Panel=WelcomePanel', 'ReadingTime=17.23s']
ReadingTime=17.23
['Panel=ButtonInstructionPanel', 'ReadingTime=6.80s']
ReadingTime=6.80
['Panel=GrabInstructionPanel', 'ReadingTime=21.00s']
ReadingTime=21.00

In [60]:
reading_time_series

17    17.23
33     6.80
71    21.00
Name: Activity_Log, dtype: float64

In [61]:
reading_time_dict['total'], reading_time_dict['mean'], reading_time_dict['max'], reading_time_dict['median'], reading_time_dict['std'] =du.calculate_duration_metric_stats(metric_series=reading_time_series)

In [62]:
reading_time_dict['intensity']=du.ratio_calculation(value1=reading_time_dict['total'],
                                                    value2=features_dict["phase_duration"])

In [63]:
reading_time_dict

{'total': np.float64(45.03),
 'mean': np.float64(15.01),
 'max': np.float64(21.0),
 'median': np.float64(17.23),
 'std': np.float64(7.36),
 'intensity': np.float64(0.92)}

#### Fill out hover_dict

In [ ]:

hover_dict = {
    "total_hover_count": None,
    "total_hover_duration": None,
    "mean_hover_duration": None,
    "max_hover_duration": None,
    "median_hover_duration": None,
    "std_hover_duration": None,
    "cv_hover_duration": None, # std_hover_duration / mean_hover_duration
    "hover_intensity": None
}

In [ ]:
combined_patterns = '|'.join(pattern_list)
    print(combined_patterns)
    matches = re.search(combined_patterns, s)

In [ ]:
patterns = [r"HoverCount=([0-9]+)", 
            r"TotalHovers=([0-9]+)"]

combined_patterns = '|'.join(patterns)
print(combined_patterns)
hover_series = df['Activity_Log'].apply(du.extract_value_from_string,pattern_list=patterns, type_to_extract=int)
hover_series

HoverCount=([0-9]+)|TotalHovers=([0-9]+)

3     None
5     None
7     None
9     None
11    None
13    None
18    None
28    None
36    None
38    None
Name: Activity_Log, dtype: object

In [37]:
hover_series.sum()

np.float64(32.0)