# 0. Library

In [27]:
import pandas as pd
from pathlib import Path
import re

import importlib
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp
from features import general_func as gf
import constants_data as cd

# Reload
importlib.reload(du)
importlib.reload(dp)
importlib.reload(gf)
importlib.reload(cd)

# 1. Paths and Constants

In [28]:
# Constants and paths
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv" / "1.output_nb_1.Patient_vector(local)_extracting" / "1.extracted_features.csv"

preprocessing_folder = parent_folder / "preprocessing"

df = pd.read_csv(df_path)

df.head()

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,MoCA_Score,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,P001,NaN,Female,Right,4,4,28.0,1,45.03,15.01,...,0.80,0.50,35,0,0.01,0.0,1275,0,0.40,0.0
1,P002,59.0,Female,Right,4,2,NaN,1,171.99,57.33,...,0.61,1.15,63,0,0.02,0.0,222,0,0.09,0.0
2,P003,82.0,Male,Right,4,1,26.0,1,338.75,112.92,...,0.75,0.61,12,0,0.00,0.0,277,0,0.09,0.0
3,P004,75.0,Male,Left,4,2,NaN,1,114.78,38.26,...,0.59,0.92,47,1,0.03,0.0,157,0,0.10,0.0
4,P005,62.0,Male,Right,4,1,27.0,1,152.90,50.97,...,0.58,0.48,28,0,0.02,0.0,125,0,0.08,0.0

In [29]:
# input df for 20 young patients
name = f"2.cleaned_features_20_young_patients.csv"
df_20_young_patients = df.loc[20:].copy() # seperate young 20 patients

df_cleaning = df_20_young_patients.drop(columns=['MoCA_Score']) # remove the target column, they are for test

In [30]:
# input for 7 old patient with
name = f"3.cleaned_features_7_young_patients.csv"

df_20_real_patients = df.loc[:19].copy()

df_nan_MoCA = df_20_real_patients[(df_20_real_patients['MoCA_Score'].isna())].copy()

In [31]:
df_cleaning

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,Tutorial_max_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
20,P021,22.0,Male,Right,4,0,1,32.97,10.99,13.79,...,0.11,0.20,4,0,0.00,0.0,65,0,0.14,0.0
21,P022,23.0,Male,Right,4,0,1,28.38,9.46,14.62,...,0.03,0.02,5,0,0.01,0.0,59,0,0.11,0.0
22,P023,23.0,Male,Right,4,0,1,52.16,17.39,24.86,...,0.45,0.28,4,0,0.01,0.0,84,0,0.15,0.0
23,P024,22.0,Male,Right,4,1,1,40.72,13.57,19.35,...,0.55,0.20,17,0,0.01,0.0,154,0,0.21,0.0
24,P025,22.0,Male,Right,4,0,1,60.58,20.19,30.96,...,0.19,0.55,8,4,0.00,0.0,76,0,0.13,0.0
25,P026,22.0,Male,Right,4,0,1,41.19,13.73,18.17,...,0.16,0.14,6,0,0.01,0.0,60,0,0.14,0.0
26,P027,22.0,Male,Right,4,0,1,38.30,12.77,22.71,...,0.24,0.12,8,0,0.01,0.0,84,0,0.15,0.0
27,P028,21.0,Male,Right,4,1,1,49.91,16.64,30.98,...,0.06,0.16,6,0,0.01,0.0,114,0,0.18,0.0
28,P029,25.0,Female,Right,4,0,1,20.68,6.89,14.25,...,0.12,0.15,7,0,0.01,0.0,84,0,0.16,0.0
29,P030,22.0,Male,Right,4,0,1,44.33,14.78,20.92,...,0.46,0.24,6,0,0.01,0.0,92,0,0.16,0.0
30,P031,22.0,Female,Right,4,1,1,51.30,17.10,28.90,...,0.15,0.14,10,0,0.01,0.0,97,0,0.20,0.0
31,P032,27.0,Female,Right,4,0,1,51.62,17.21,28.12,...,0.27,0.14,16,0,0.02,0.0,78,0,0.13,0.0
32,P033,22.0,Male,Right,4,1,1,44.86,14.95,26.62,...,0.05,0.04,12,9,0.01,0.0,92,0,0.13,0.0
33,P034,21.0,Male,Right,4,0,1,27.61,9.20,16.67,...,0.10,0.14,9,0,0.01,0.0,78,0,0.11,0.0
34,P035,22.0,Male,Right,4,0,1,33.65,11.22,19.10,...,0.10,0.15,12,0,0.01,0.0,69,0,0.13,0.0
35,P036,22.0,Male,Right,4,0,1,30.95,10.32,18.43,...,0.02,0.03,22,0,0.02,0.0,160,2,0.22,0.0
36,P037,21.0,Female,Right,4,1,1,73.57,24.52,58.70,...,0.20,0.17,5,0,0.01,0.0,118,0,0.15,0.0
37,P038,20.0,Female,Right,4,0,1,36.94,12.31,30.03,...,0.15,0.08,11,0,0.01,0.0,104,4,0.12,0.0
38,P039,21.0,Male,Right,4,1,1,56.26,18.75,41.04,...,0.02,0.02,5,0,0.00,0.0,147,0,0.23,0.0
39,P040,22.0,Male,Right,4,0,1,27.88,9.29,12.49,...,0.21,0.15,16,0,0.03,0.0,103,1,0.18,0.0

# 2. Data preprocessing

In [32]:
df_cleaning = dp.check_Nan_values(original_df= df_cleaning, missing_values_threshold=0.6)

Missing values found, number of columns with Nan values : 3
{'Tutorial_std_duration_gaze': 1, 'ObjectRecognition_std_duration_gaze': 6, 'Memory_cognitive_freez_mean_duration': 20}
Removed columns :['Memory_cognitive_freez_mean_duration']
All Nan values are handled successfuly.

In [33]:
df_cleaning = dp.check_columns_type(df_without_Nan= df_cleaning)

Columns before one hot encoding :

          Total columns :375,
          Numerical columns : 372,
          Categorical columns : 3,
          Unkown columns : 0


 Columns after one hot encoding :

          Total columns :373,
          Numerical columns : 373,
          Categorical columns : 0,
          Unkown columns : 0

All Categorical columns are encoded successfuly.

In [34]:
with open(preprocessing_folder/"columns_to_remove.txt", "r") as f:
    columns_to_remove = [line.strip() for line in f.readlines()]

columns_to_remove

['Memory_median_duration_gaze',
 'Tutorial_dominant_hand_mean_speed',
 'ObjectRecognition_max_duration_gaze',
 'Visuospatial_head_total_orientation',
 'Memory_not_dominant_hand_max_speed',
 'ObjectRecognition_HMD_Z_std',
 'Memory_dominant_hand_y_range',
 'ObjectRecognition_mean_choose_wrong_obj',
 'Visuospatial_not_dominant_hand_total_distance',
 'Tutorial_std_duration_press',
 'ObjectRecognition_gaze_switch_count',
 'Tutorial_interaction_fraction',
 'Visuospatial_not_dominant_hand_x_range',
 'ObjectRecognition_head_total_orientation',
 'Memory_dominant_hand_x_range',
 'Tutorial_mean_duration_gaze',
 'Tutorial_hover_vs_reading_time_ratio',
 'Tutorial_hover_vs_active_interaction_ratio',
 'Tutorial_max_duration_press',
 'Memory_hover_vs_active_interaction_ratio',
 'ObjectRecognition_decision_latency',
 'Tutorial_intensity_press',
 'Visuospatial_not_dominant_hand_max_speed',
 'ObjectRecognition_intensity_press',
 'Memory_max_head_speed_in_orientation',
 'ObjectRecognition_Yaw_range',
 'ObjectRecognition_dominant_hand_mean_speed',
 'ObjectRecognition_std_duration_gaze',
 'Tutorial_dominant_hand_y_range',
 'ObjectRecognition_dominant_hand_max_speed',
 'ObjectRecognition_not_dominant_hand_mean_speed',
 'ObjectRecognition_not_dominant_hand_total_distance',
 'ObjectRecognition_gaze_obj_looked_ratio',
 'Tutorial_intensity_hover',
 'ObjectRecognition_intensity_grab',
 'Tutorial_intensity_grab',
 'ObjectRecognition_not_dominant_hand_grip_count',
 'Visuospatial_total_count_press',
 'ObjectRecognition_not_dominant_hand_z_range',
 'ObjectRecognition_time_before_first_hover',
 'ObjectRecognition_not_dominant_hand_x_range',
 'Visuospatial_total_count_hover',
 'Tutorial_mean_duration_press',
 'Visuospatial_hovers_per_click',
 'ObjectRecognition_not_dominant_hand_y_range',
 'Visuospatial_not_dominant_hand_y_range',
 'ObjectRecognition_hover_vs_active_interaction_ratio',
 'ObjectRecognition_HMD_Y_std',
 'ObjectRecognition_max_duration_hover',
 'Visuospatial_not_dominant_hand_z_range',
 'ObjectRecognition_score',
 'Tutorial_total_duration_press',
 'ObjectRecognition_total_duration_hover',
 'Visuospatial_hover_vs_reading_time_ratio',
 'ObjectRecognition_hover_vs_reading_time_ratio',
 'ObjectRecognition_mean_duration_hover',
 'Memory_mean_head_speed_in_distance',
 'Memory_HMD_Z_std',
 'Tutorial_max_head_speed_in_distance',
 'ObjectRecognition_not_dominant_hand_max_speed',
 'Visuospatial_Pitch_std',
 'ObjectRecognition_max_head_speed_in_distance',
 'Memory_hover_vs_reading_time_ratio',
 'ObjectRecognition_std_duration_hover',
 'ObjectRecognition_mean_duration_press',
 'ObjectRecognition_mean_duration_gaze',
 'Memory_not_dominant_hand_trigger_pressure_mean',
 'Visuospatial_not_dominant_hand_trigger_press_count',
 'ObjectRecognition_median_duration_press',
 'ObjectRecognition_dominant_hand_total_distance',
 'ObjectRecognition_total_duration_press',
 'Memory_std_head_speed_in_distance',
 'Memory_not_dominant_hand_trigger_press_count',
 'Tutorial_total_duration_gaze',
 'ObjectRecognition_dominant_hand_y_range',
 'Memory_not_dominant_hand_total_distance',
 'Memory_gaze_switch_count',
 'ObjectRecognition_hovers_per_click',
 'ObjectRecognition_Pitch_range',
 'Memory_not_dominant_hand_x_range',
 'Tutorial_not_dominant_hand_max_speed',
 'Tutorial_std_head_speed_in_orientation',
 'ObjectRecognition_max_duration_press',
 'Tutorial_mean_head_speed_in_orientation',
 'Tutorial_time_before_first_hover',
 'Tutorial_std_reading_time',
 'Visuospatial_Yaw_range',
 'Memory_median_duration_hover',
 'Memory_hovers_per_click',
 'ObjectRecognition_total_count_hover',
 'Memory_mean_head_speed_in_orientation',
 'Memory_total_count_grab',
 'Visuospatial_dominant_hand_z_range',
 'Memory_dominant_hand_max_speed',
 'ObjectRecognition_median_duration_grab',
 'Tutorial_median_duration_grab',
 'Tutorial_dominant_hand_grip_mean',
 'Visuospatial_intensity_reading_time',
 'Visuospatial_intensity_hover',
 'Memory_std_head_speed_in_orientation',
 'ObjectRecognition_std_duration_press',
 'Tutorial_HMD_X_std',
 'ObjectRecognition_total_count_press',
 'Tutorial_Pitch_std',
 'ObjectRecognition_mean_duration_grab',
 'Tutorial_mean_duration_grab',
 'Tutorial_total_count_grab',
 'ObjectRecognition_total_count_grab',
 'Visuospatial_interaction_fraction',
 'Tutorial_mean_head_speed_in_distance',
 'ObjectRecognition_HMD_X_std',
 'Memory_total_wrong_recall',
 'ObjectRecognition_HMD_X_range',
 'Memory_time_before_first_hover',
 'ObjectRecognition_median_duration_hover',
 'ObjectRecognition_std_duration_grab',
 'Tutorial_std_duration_grab',
 'Memory_total_count_hover',
 'ObjectRecognition_max_head_speed_in_orientation',
 'Memory_HMD_Y_range',
 'ObjectRecognition_max_duration_grab',
 'Tutorial_max_duration_grab',
 'Tutorial_HMD_X_range',
 'Tutorial_not_dominant_hand_y_range',
 'ObjectRecognition_std_reading_time',
 'Tutorial_median_duration_hover',
 'Visuospatial_decision_latency',
 'Visuospatial_max_head_speed_in_distance',
 'ObjectRecognition_dominant_hand_x_range',
 'Visuospatial_dominant_hand_max_speed',
 'Memory_not_dominant_hand_z_range',
 'Memory_Pitch_range',
 'Tutorial_hovers_per_click',
 'Visuospatial_HMD_X_range',
 'Tutorial_mean_reading_time',
 'Tutorial_max_reading_time',
 'Tutorial_median_reading_time',
 'Tutorial_std_duration_hover',
 'Tutorial_std_duration_gaze',
 'Tutorial_clicks_per_second',
 'Tutorial_time_before_first_press',
 'Tutorial_HMD_Z_range',
 'Tutorial_std_head_speed_in_distance',
 'Tutorial_Yaw_range',
 'Tutorial_gaze_obj_looked_ratio',
 'Tutorial_gaze_switch_count',
 'Tutorial_dominant_hand_total_distance',
 'Tutorial_not_dominant_hand_total_distance',
 'Tutorial_dominant_hand_z_range',
 'Tutorial_not_dominant_hand_z_range',
 'Tutorial_not_dominant_hand_trigger_press_count',
 'Tutorial_not_dominant_hand_trigger_pressure_mean',
 'Tutorial_not_dominant_hand_grip_count',
 'Tutorial_not_dominant_hand_grip_mean',
 'ObjectRecognition_total_duration_grab',
 'ObjectRecognition_interaction_fraction',
 'ObjectRecognition_clicks_per_second',
 'ObjectRecognition_mean_success_duration',
 'ObjectRecognition_total_duration',
 'ObjectRecognition_std_head_speed_in_orientation',
 'ObjectRecognition_dominant_hand_trigger_press_count',
 'ObjectRecognition_dominant_hand_trigger_pressure_mean',
 'ObjectRecognition_dominant_hand_grip_mean',
 'Visuospatial_mean_reading_time',
 'Visuospatial_max_reading_time',
 'Visuospatial_median_reading_time',
 'Visuospatial_std_reading_time',
 'Visuospatial_mean_duration_hover',
 'Visuospatial_max_duration_hover',
 'Visuospatial_std_duration_hover',
 'Visuospatial_total_duration_press',
 'Visuospatial_mean_duration_press',
 'Visuospatial_max_duration_press',
 'Visuospatial_median_duration_press',
 'Visuospatial_std_duration_press',
 'Visuospatial_total_duration_grab',
 'Visuospatial_mean_duration_grab',
 'Visuospatial_max_duration_grab',
 'Visuospatial_median_duration_grab',
 'Visuospatial_std_duration_grab',
 'Visuospatial_total_duration_gaze',
 'Visuospatial_mean_duration_gaze',
 'Visuospatial_max_duration_gaze',
 'Visuospatial_std_duration_gaze',
 'Visuospatial_intensity_gaze',
 'Visuospatial_time_before_first_press',
 'Visuospatial_time_before_first_hover',
 'Visuospatial_total_wrong_placement',
 'Visuospatial_total_duration',
 'Visuospatial_HMD_X_std',
 'Visuospatial_std_head_speed_in_distance',
 'Visuospatial_Roll_range',
 'Visuospatial_std_head_speed_in_orientation',
 'Visuospatial_gaze_obj_looked_ratio',
 'Visuospatial_gaze_switch_count',
 'Visuospatial_dominant_hand_mean_speed',
 'Visuospatial_not_dominant_hand_mean_speed',
 'Visuospatial_dominant_hand_trigger_press_count',
 'Visuospatial_dominant_hand_trigger_pressure_mean',
 'Visuospatial_dominant_hand_grip_count',
 'Memory_total_reading_time',
 'Memory_mean_reading_time',
 'Memory_max_reading_time',
 'Memory_std_reading_time',
 'Memory_total_duration_hover',
 'Memory_std_duration_hover',
 'Memory_total_duration_press',
 'Memory_mean_duration_press',
 'Memory_max_duration_press',
 'Memory_std_duration_press',
 'Memory_intensity_press',
 'Memory_total_duration_grab',
 'Memory_mean_duration_grab',
 'Memory_max_duration_grab',
 'Memory_median_duration_grab',
 'Memory_std_duration_grab',
 'Memory_intensity_grab',
 'Memory_total_count_gaze',
 'Memory_total_duration_gaze',
 'Memory_std_duration_gaze',
 'Memory_interaction_fraction',
 'Memory_mean_recall',
 'Memory_cognitive_freez_count',
 'Memory_total_duration',
 'Memory_head_total_orientation',
 'Memory_gaze_obj_looked_ratio',
 'Memory_dominant_hand_total_distance',
 'Memory_dominant_hand_trigger_press_count',
 'Memory_dominant_hand_trigger_pressure_mean',
 'Memory_dominant_hand_grip_count',
 'Memory_not_dominant_hand_grip_count',
 'Memory_dominant_hand_grip_mean',
 'dominant_hand_Right']

In [35]:
col = columns_to_remove.remove('dominant_hand_Right')

In [36]:
df_cleaning = df_cleaning.drop(columns=columns_to_remove)
df_cleaning.shape

(20, 141)

In [37]:
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv" / "2.output_nb_2.1Data_preprocessing" /"3.cleaned_features_13_patients.csv"

df_13 = pd.read_csv(df_path)

df_13.head()

FileNotFoundError: [Errno 2] No such file or directory: '../../data/produced_csv/2.output_nb_2.1Data_preprocessing/3.cleaned_features_13_patients.csv'

In [ ]:
extra_useless_columns = set(df_cleaning.columns.to_list()) - set(df_13.columns.to_list())

In [ ]:
df_cleaning = df_cleaning.drop(columns=extra_useless_columns)
df_cleaning.shape

(20, 112)

In [ ]:
# save df
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv"
df_cleaning.to_csv(df_path / name, index=False)