# 0. Library

In [58]:
import pandas as pd

import importlib
import sys
sys.path.append('../') 
from features import data_pipeline as dp
import constants_data as cd
import paths_data as paths

# Reload
importlib.reload(dp)
importlib.reload(cd)
importlib.reload(paths)

# 1. Paths and Constants

In [59]:
# Constants and paths
proceed_folder = paths.STAGE_THREE_DATA_PREPROCESSING # path to save the output

df_path = paths.STAGE_TWO_FEATURE_EXTRACTION / cd.FEATURE_EXTRACTION_Df_NAME # path to read the input
df = pd.read_csv(df_path)

df.head()

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,MoCA_Score,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,P001,NaN,Female,Right,4,4,28.0,1,45.03,15.01,...,0.80,0.50,35,0,0.01,0.0,1275,0,0.40,0.0
1,P002,59.0,Female,Right,4,2,NaN,1,171.99,57.33,...,0.61,1.15,63,0,0.02,0.0,222,0,0.09,0.0
2,P003,82.0,Male,Right,4,1,26.0,1,338.75,112.92,...,0.75,0.61,12,0,0.00,0.0,277,0,0.09,0.0
3,P004,75.0,Male,Left,4,2,NaN,1,114.78,38.26,...,0.59,0.92,47,1,0.03,0.0,157,0,0.10,0.0
4,P005,62.0,Male,Right,4,1,27.0,1,152.90,50.97,...,0.58,0.48,28,0,0.02,0.0,125,0,0.08,0.0

## 1.1 input data

In [60]:
# input df for 20 young patients
"""df_20_young_patients = df.loc[20:].copy() # seperate young 20 patients

df_cleaning = df_20_young_patients.drop(columns=['MoCA_Score']) # remove the target column, they are for test
name_df_output = cd.name_20_young_patients"""

"df_20_young_patients = df.loc[20:].copy() # seperate young 20 patients\n\ndf_cleaning = df_20_young_patients.drop(columns=['MoCA_Score']) # remove the target column, they are for test\nname_df_output = cd.name_20_young_patients"

In [ ]:
# input for 7 old patient with / uncomment it
df_20_real_patients = df.loc[:19].copy()
df_cleaning = df_20_real_patients[(df_20_real_patients['MoCA_Score'].isna())].copy()
name_df_output = cd.name_7_old_patients

In [62]:
df_cleaning

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,MoCA_Score,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
1,P002,59.0,Female,Right,4,2,NaN,1,171.99,57.33,...,0.61,1.15,63,0,0.02,0.0,222,0,0.09,0.0
3,P004,75.0,Male,Left,4,2,NaN,1,114.78,38.26,...,0.59,0.92,47,1,0.03,0.0,157,0,0.10,0.0
8,P009,73.0,Male,Right,4,3,NaN,1,198.53,66.18,...,0.59,0.72,631,0,0.23,0.0,630,0,0.21,0.0
12,P013,61.0,Female,Right,4,2,NaN,1,109.99,36.66,...,0.41,0.19,14,0,0.01,0.0,136,0,0.13,0.0
15,P016,75.0,Female,Right,4,2,NaN,1,260.47,86.82,...,0.47,0.69,65,0,0.03,0.0,136,0,0.11,0.0
16,P017,76.0,Female,Right,4,2,NaN,1,241.54,80.51,...,0.49,0.70,10,0,0.01,0.0,233,0,0.18,0.0
18,P019,70.0,Male,Right,4,2,NaN,1,279.39,93.13,...,0.54,0.79,284,0,0.20,0.0,273,0,0.20,0.0

# 2. Data preprocessing

In [63]:
df_cleaning = dp.check_Nan_values(original_df= df_cleaning, missing_values_threshold=0.6)

Missing values found, number of columns with Nan values : 3
{'MoCA_Score': 7, 'ObjectRecognition_std_duration_gaze': 2, 'Memory_cognitive_freez_mean_duration': 6}
Removed columns :['MoCA_Score', 'Memory_cognitive_freez_mean_duration']
All Nan values are handled successfuly.

In [64]:
df_cleaning = dp.check_columns_type(df_without_Nan= df_cleaning)

Columns before one hot encoding :

          Total columns :375,
          Numerical columns : 372,
          Categorical columns : 3,
          Unkown columns : 0


 Columns after one hot encoding :

          Total columns :374,
          Numerical columns : 374,
          Categorical columns : 0,
          Unkown columns : 0

All Categorical columns are encoded successfuly.

In [65]:
with open(paths.COLUMNS_TO_REMOVE, "r") as f:
    columns_to_remove = [line.strip() for line in f.readlines()]

columns_to_remove

['Memory_median_duration_gaze',
 'Tutorial_dominant_hand_mean_speed',
 'ObjectRecognition_max_duration_gaze',
 'Visuospatial_head_total_orientation',
 'Memory_not_dominant_hand_max_speed',
 'ObjectRecognition_HMD_Z_std',
 'Memory_dominant_hand_y_range',
 'ObjectRecognition_mean_choose_wrong_obj',
 'Visuospatial_not_dominant_hand_total_distance',
 'Tutorial_std_duration_press',
 'ObjectRecognition_gaze_switch_count',
 'Tutorial_interaction_fraction',
 'Visuospatial_not_dominant_hand_x_range',
 'ObjectRecognition_head_total_orientation',
 'Memory_dominant_hand_x_range',
 'Tutorial_mean_duration_gaze',
 'Tutorial_hover_vs_reading_time_ratio',
 'Tutorial_hover_vs_active_interaction_ratio',
 'Tutorial_max_duration_press',
 'Memory_hover_vs_active_interaction_ratio',
 'ObjectRecognition_decision_latency',
 'Tutorial_intensity_press',
 'Visuospatial_not_dominant_hand_max_speed',
 'ObjectRecognition_intensity_press',
 'Memory_max_head_speed_in_orientation',
 'ObjectRecognition_Yaw_range',
 'ObjectRecognition_dominant_hand_mean_speed',
 'ObjectRecognition_std_duration_gaze',
 'Tutorial_dominant_hand_y_range',
 'ObjectRecognition_dominant_hand_max_speed',
 'ObjectRecognition_not_dominant_hand_mean_speed',
 'ObjectRecognition_not_dominant_hand_total_distance',
 'ObjectRecognition_gaze_obj_looked_ratio',
 'Tutorial_intensity_hover',
 'ObjectRecognition_intensity_grab',
 'Tutorial_intensity_grab',
 'ObjectRecognition_not_dominant_hand_grip_count',
 'Visuospatial_total_count_press',
 'ObjectRecognition_not_dominant_hand_z_range',
 'ObjectRecognition_time_before_first_hover',
 'ObjectRecognition_not_dominant_hand_x_range',
 'Visuospatial_total_count_hover',
 'Tutorial_mean_duration_press',
 'Visuospatial_hovers_per_click',
 'ObjectRecognition_not_dominant_hand_y_range',
 'Visuospatial_not_dominant_hand_y_range',
 'ObjectRecognition_hover_vs_active_interaction_ratio',
 'ObjectRecognition_HMD_Y_std',
 'ObjectRecognition_max_duration_hover',
 'Visuospatial_not_dominant_hand_z_range',
 'ObjectRecognition_score',
 'Tutorial_total_duration_press',
 'ObjectRecognition_total_duration_hover',
 'Visuospatial_hover_vs_reading_time_ratio',
 'ObjectRecognition_hover_vs_reading_time_ratio',
 'ObjectRecognition_mean_duration_hover',
 'Memory_mean_head_speed_in_distance',
 'Memory_HMD_Z_std',
 'Tutorial_max_head_speed_in_distance',
 'ObjectRecognition_not_dominant_hand_max_speed',
 'Visuospatial_Pitch_std',
 'ObjectRecognition_max_head_speed_in_distance',
 'Memory_hover_vs_reading_time_ratio',
 'ObjectRecognition_std_duration_hover',
 'ObjectRecognition_mean_duration_press',
 'ObjectRecognition_mean_duration_gaze',
 'Memory_not_dominant_hand_trigger_pressure_mean',
 'Visuospatial_not_dominant_hand_trigger_press_count',
 'ObjectRecognition_median_duration_press',
 'ObjectRecognition_dominant_hand_total_distance',
 'ObjectRecognition_total_duration_press',
 'Memory_std_head_speed_in_distance',
 'Memory_not_dominant_hand_trigger_press_count',
 'Tutorial_total_duration_gaze',
 'ObjectRecognition_dominant_hand_y_range',
 'Memory_not_dominant_hand_total_distance',
 'Memory_gaze_switch_count',
 'ObjectRecognition_hovers_per_click',
 'ObjectRecognition_Pitch_range',
 'Memory_not_dominant_hand_x_range',
 'Tutorial_not_dominant_hand_max_speed',
 'Tutorial_std_head_speed_in_orientation',
 'ObjectRecognition_max_duration_press',
 'Tutorial_mean_head_speed_in_orientation',
 'Tutorial_time_before_first_hover',
 'Tutorial_std_reading_time',
 'Visuospatial_Yaw_range',
 'Memory_median_duration_hover',
 'Memory_hovers_per_click',
 'ObjectRecognition_total_count_hover',
 'Memory_mean_head_speed_in_orientation',
 'Memory_total_count_grab',
 'Visuospatial_dominant_hand_z_range',
 'Memory_dominant_hand_max_speed',
 'ObjectRecognition_median_duration_grab',
 'Tutorial_median_duration_grab',
 'Tutorial_dominant_hand_grip_mean',
 'Visuospatial_intensity_reading_time',
 'Visuospatial_intensity_hover',
 'Memory_std_head_speed_in_orientation',
 'ObjectRecognition_std_duration_press',
 'Tutorial_HMD_X_std',
 'ObjectRecognition_total_count_press',
 'Tutorial_Pitch_std',
 'ObjectRecognition_mean_duration_grab',
 'Tutorial_mean_duration_grab',
 'Tutorial_total_count_grab',
 'ObjectRecognition_total_count_grab',
 'Visuospatial_interaction_fraction',
 'Tutorial_mean_head_speed_in_distance',
 'ObjectRecognition_HMD_X_std',
 'Memory_total_wrong_recall',
 'ObjectRecognition_HMD_X_range',
 'Memory_time_before_first_hover',
 'ObjectRecognition_median_duration_hover',
 'ObjectRecognition_std_duration_grab',
 'Tutorial_std_duration_grab',
 'Memory_total_count_hover',
 'ObjectRecognition_max_head_speed_in_orientation',
 'Memory_HMD_Y_range',
 'ObjectRecognition_max_duration_grab',
 'Tutorial_max_duration_grab',
 'Tutorial_HMD_X_range',
 'Tutorial_not_dominant_hand_y_range',
 'ObjectRecognition_std_reading_time',
 'Tutorial_median_duration_hover',
 'Visuospatial_decision_latency',
 'Visuospatial_max_head_speed_in_distance',
 'ObjectRecognition_dominant_hand_x_range',
 'Visuospatial_dominant_hand_max_speed',
 'Memory_not_dominant_hand_z_range',
 'Memory_Pitch_range',
 'Tutorial_hovers_per_click',
 'Visuospatial_HMD_X_range',
 'Tutorial_mean_reading_time',
 'Tutorial_max_reading_time',
 'Tutorial_median_reading_time',
 'Tutorial_std_duration_hover',
 'Tutorial_std_duration_gaze',
 'Tutorial_clicks_per_second',
 'Tutorial_time_before_first_press',
 'Tutorial_HMD_Z_range',
 'Tutorial_std_head_speed_in_distance',
 'Tutorial_Yaw_range',
 'Tutorial_gaze_obj_looked_ratio',
 'Tutorial_gaze_switch_count',
 'Tutorial_dominant_hand_total_distance',
 'Tutorial_not_dominant_hand_total_distance',
 'Tutorial_dominant_hand_z_range',
 'Tutorial_not_dominant_hand_z_range',
 'Tutorial_not_dominant_hand_trigger_press_count',
 'Tutorial_not_dominant_hand_trigger_pressure_mean',
 'Tutorial_not_dominant_hand_grip_count',
 'Tutorial_not_dominant_hand_grip_mean',
 'ObjectRecognition_total_duration_grab',
 'ObjectRecognition_interaction_fraction',
 'ObjectRecognition_clicks_per_second',
 'ObjectRecognition_mean_success_duration',
 'ObjectRecognition_total_duration',
 'ObjectRecognition_std_head_speed_in_orientation',
 'ObjectRecognition_dominant_hand_trigger_press_count',
 'ObjectRecognition_dominant_hand_trigger_pressure_mean',
 'ObjectRecognition_dominant_hand_grip_mean',
 'Visuospatial_mean_reading_time',
 'Visuospatial_max_reading_time',
 'Visuospatial_median_reading_time',
 'Visuospatial_std_reading_time',
 'Visuospatial_mean_duration_hover',
 'Visuospatial_max_duration_hover',
 'Visuospatial_std_duration_hover',
 'Visuospatial_total_duration_press',
 'Visuospatial_mean_duration_press',
 'Visuospatial_max_duration_press',
 'Visuospatial_median_duration_press',
 'Visuospatial_std_duration_press',
 'Visuospatial_total_duration_grab',
 'Visuospatial_mean_duration_grab',
 'Visuospatial_max_duration_grab',
 'Visuospatial_median_duration_grab',
 'Visuospatial_std_duration_grab',
 'Visuospatial_total_duration_gaze',
 'Visuospatial_mean_duration_gaze',
 'Visuospatial_max_duration_gaze',
 'Visuospatial_std_duration_gaze',
 'Visuospatial_intensity_gaze',
 'Visuospatial_time_before_first_press',
 'Visuospatial_time_before_first_hover',
 'Visuospatial_total_wrong_placement',
 'Visuospatial_total_duration',
 'Visuospatial_HMD_X_std',
 'Visuospatial_std_head_speed_in_distance',
 'Visuospatial_Roll_range',
 'Visuospatial_std_head_speed_in_orientation',
 'Visuospatial_gaze_obj_looked_ratio',
 'Visuospatial_gaze_switch_count',
 'Visuospatial_dominant_hand_mean_speed',
 'Visuospatial_not_dominant_hand_mean_speed',
 'Visuospatial_dominant_hand_trigger_press_count',
 'Visuospatial_dominant_hand_trigger_pressure_mean',
 'Visuospatial_dominant_hand_grip_count',
 'Memory_total_reading_time',
 'Memory_mean_reading_time',
 'Memory_max_reading_time',
 'Memory_std_reading_time',
 'Memory_total_duration_hover',
 'Memory_std_duration_hover',
 'Memory_total_duration_press',
 'Memory_mean_duration_press',
 'Memory_max_duration_press',
 'Memory_std_duration_press',
 'Memory_intensity_press',
 'Memory_total_duration_grab',
 'Memory_mean_duration_grab',
 'Memory_max_duration_grab',
 'Memory_median_duration_grab',
 'Memory_std_duration_grab',
 'Memory_intensity_grab',
 'Memory_total_count_gaze',
 'Memory_total_duration_gaze',
 'Memory_std_duration_gaze',
 'Memory_interaction_fraction',
 'Memory_mean_recall',
 'Memory_cognitive_freez_count',
 'Memory_total_duration',
 'Memory_head_total_orientation',
 'Memory_gaze_obj_looked_ratio',
 'Memory_dominant_hand_total_distance',
 'Memory_dominant_hand_trigger_press_count',
 'Memory_dominant_hand_trigger_pressure_mean',
 'Memory_dominant_hand_grip_count',
 'Memory_not_dominant_hand_grip_count',
 'Memory_dominant_hand_grip_mean',
 'dominant_hand_Right']

In [66]:
col = columns_to_remove.remove('dominant_hand_Right')

In [67]:
df_cleaning = df_cleaning.drop(columns=columns_to_remove)
df_cleaning.shape

(7, 142)

In [68]:
df_path = paths.STAGE_THREE_DATA_PREPROCESSING / "cleaned_features_13_patients.csv"

df_13 = pd.read_csv(df_path)

df_13.head()

,Age,Help_Rating_out_of_5,MoCA_Score,Tutorial_total_reading_time,Tutorial_intensity_reading_time,Tutorial_total_count_hover,Tutorial_total_duration_hover,Tutorial_mean_duration_hover,Tutorial_max_duration_hover,Tutorial_total_count_press,...,Memory_Yaw_std,Memory_Pitch_std,Memory_Roll_std,Memory_Yaw_range,Memory_Roll_range,Memory_dominant_hand_mean_speed,Memory_not_dominant_hand_mean_speed,Memory_dominant_hand_z_range,Memory_not_dominant_hand_y_range,Gender_Male
0,73.0,4,28.0,45.03,0.92,32,20.64,1.03,2.29,8,...,26.23,161.72,177.36,99.05,360.00,0.16,0.03,0.82,0.80,0
1,82.0,1,26.0,338.75,0.99,688,145.79,2.11,20.01,9,...,23.27,161.90,162.61,109.38,359.99,0.06,0.01,0.98,0.75,1
2,62.0,1,27.0,152.90,0.97,61,54.33,1.81,11.62,8,...,30.07,170.64,169.17,248.93,359.98,0.12,0.02,1.05,0.58,1
3,78.0,2,27.0,181.69,0.98,26,91.62,2.78,23.45,9,...,31.96,136.51,170.83,174.64,359.98,0.12,0.02,0.82,0.42,0
4,71.0,2,26.0,190.51,0.98,109,102.68,2.57,21.86,8,...,27.48,169.32,125.66,146.78,359.99,0.11,0.03,0.82,0.64,0

In [69]:
extra_useless_columns = set(df_cleaning.columns.to_list()) - set(df_13.columns.to_list())

In [70]:
df_cleaning = df_cleaning.drop(columns=extra_useless_columns)
df_cleaning.shape

(7, 112)

# 3. Save DF

In [71]:
df_cleaning.to_csv(proceed_folder / name_df_output, index=False)