# 0. Library

In [17]:
import pandas as pd
from pathlib import Path
import re

import importlib
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp
from features import general_func as gf
import constants_data as cd

# Reload
importlib.reload(du)
importlib.reload(dp)
importlib.reload(gf)
importlib.reload(cd)

# 1. Paths and Constants

In [18]:
# Constants and paths
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path   = parent_folder / "data" / "produced_csv" / "1.extracted_features.csv"
 
df = pd.read_csv(df_path)

df.head()

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,Tutorial_max_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,P001,NaN,Female,Right,4,1,1,45.03,15.01,21.00,...,0.80,0.50,35,0,0.01,0.0,1275,0,0.40,0.0
1,P002,59.0,Female,Right,4,3,1,171.99,57.33,91.56,...,0.61,1.15,63,0,0.02,0.0,222,0,0.09,0.0
2,P003,82.0,Male,Right,4,4,1,338.75,112.92,155.14,...,0.75,0.61,12,0,0.00,0.0,277,0,0.09,0.0
3,P004,75.0,Male,Left,4,3,1,114.78,38.26,68.19,...,0.59,0.92,47,1,0.03,0.0,157,0,0.10,0.0
4,P005,62.0,Male,Right,4,4,1,152.90,50.97,88.47,...,0.58,0.48,28,0,0.02,0.0,125,0,0.08,0.0

In [20]:
df_cleaning = df.copy()

# 2. Data preprocessing

## 2.1 Fill missing values

In [ ]:
df_cleaning = dp.check_Nan_values(original_df= df_cleaning, missing_values_threshold=0.6)

Missing values found, number of columns with Nan values : 3
All Nan values are handled successfuly.

In [ ]:
df_cleaning = dp.check_columns_type(df_without_Nan= df_cleaning)

In [22]:
df_columns = df.columns.tolist()
clean_df   = df.copy()

numerical_cols   = []
categorical_cols = []
unkown_cols      = []

for col in df_columns:
    
    if not pd.api.types.is_numeric_dtype(clean_df[col]): # categorical
        categorical_cols.append(col)
    elif pd.api.types.is_numeric_dtype(clean_df[col]): # numerical
        numerical_cols.append(col)
    else:
        unkown_cols.append(col)

len(df_columns), len(numerical_cols), len(categorical_cols), len(unkown_cols)

(376, 373, 3, 0)

In [23]:
clean_df[numerical_cols]

,Age,Sessions_Completed_out_of_4,Help_Rating_out_of_5,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,Tutorial_max_reading_time,Tutorial_median_reading_time,Tutorial_std_reading_time,Tutorial_intensity_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,NaN,4,1,1,45.03,15.01,21.00,17.23,7.36,0.92,...,0.80,0.50,35,0,0.01,0.00,1275,0,0.40,0.0
1,59.0,4,3,1,171.99,57.33,91.56,69.81,41.89,0.98,...,0.61,1.15,63,0,0.02,0.00,222,0,0.09,0.0
2,82.0,4,4,1,338.75,112.92,155.14,147.97,67.02,0.99,...,0.75,0.61,12,0,0.00,0.00,277,0,0.09,0.0
3,75.0,4,3,1,114.78,38.26,68.19,43.00,32.56,0.97,...,0.59,0.92,47,1,0.03,0.00,157,0,0.10,0.0
4,62.0,4,4,1,152.90,50.97,88.47,42.24,33.99,0.97,...,0.58,0.48,28,0,0.02,0.00,125,0,0.08,0.0
5,78.0,4,3,1,181.69,60.56,90.17,75.06,38.93,0.98,...,0.42,0.71,244,0,0.12,0.00,261,0,0.13,0.0
6,71.0,4,3,1,190.51,63.50,83.86,57.69,18.16,0.98,...,0.64,0.46,12,0,0.01,0.00,159,0,0.11,0.0
7,69.0,4,4,1,208.51,69.50,99.78,67.13,29.16,0.98,...,0.33,0.92,27,0,0.02,0.00,127,0,0.08,0.0
8,73.0,4,2,1,198.53,66.18,94.27,90.08,45.08,0.98,...,0.59,0.72,631,0,0.23,0.00,630,0,0.21,0.0
9,81.0,4,3,1,265.83,88.61,115.47,95.42,30.83,0.99,...,0.63,0.69,284,0,0.18,0.00,799,0,0.21,0.0
10,74.0,4,3,1,210.34,70.11,79.48,70.82,9.74,0.98,...,0.33,0.22,12,0,0.01,0.00,159,0,0.14,0.0
11,65.0,4,3,1,164.28,54.76,60.26,58.93,8.40,0.98,...,0.46,0.38,8,0,0.01,0.00,112,0,0.10,0.0
12,61.0,4,3,1,109.99,36.66,62.12,31.25,23.23,0.96,...,0.41,0.19,14,0,0.01,0.00,136,0,0.13,0.0
13,79.0,4,1,1,534.07,178.02,206.77,197.68,42.16,0.99,...,0.79,0.66,1457,2,0.40,0.00,1545,11,0.44,0.0
14,74.0,4,3,1,269.98,89.99,180.21,66.22,80.99,0.99,...,0.38,0.70,46,0,0.04,0.00,173,0,0.15,0.0
15,75.0,4,3,1,260.47,86.82,122.55,121.28,60.78,0.98,...,0.47,0.69,65,0,0.03,0.00,136,0,0.11,0.0
16,76.0,4,3,1,241.54,80.51,184.65,45.79,91.84,0.98,...,0.49,0.70,10,0,0.01,0.00,233,0,0.18,0.0
17,69.0,4,3,1,371.73,123.91,194.47,137.26,78.10,0.99,...,0.70,0.76,58,116,0.03,0.01,171,4,0.13,0.0
18,70.0,4,3,1,279.39,93.13,178.58,88.00,83.00,0.99,...,0.54,0.79,284,0,0.20,0.00,273,0,0.20,0.0
19,72.0,4,3,1,201.54,67.18,95.63,87.69,42.59,0.98,...,0.41,0.26,57,0,0.03,0.00,250,0,0.18,0.0

In [1]:
# convert categorical column to numerical
clean_df[categorical_cols]

NameError: name 'clean_df' is not defined

In [21]:
# convert Gender and Dominant hand into binary columns
pd.get_dummies(clean_df, columns=["Gender"])
pd.get_dummies(clean_df, columns=["dominant_hand"])

clean_df["Female"] = clean_df["Gender"].map({"Female": 1, "Male": 0})
clean_df["Right_hand"] = clean_df["dominant_hand"].map({"Right": 1, "Left": 0})

clean_df = clean_df.drop(columns=categorical_cols)

In [22]:
clean_df.head()

,Age,Sessions_Completed_out_of_4,Help_Rating_out_of_5,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,Tutorial_max_reading_time,Tutorial_median_reading_time,Tutorial_std_reading_time,Tutorial_intensity_reading_time,...,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean,Female,Right_hand
0,NaN,4,1,1,45.03,15.01,21.00,17.23,7.36,0.92,...,35,0,0.01,0.0,1275,0,0.40,0.0,1,1
1,59.0,4,3,1,171.99,57.33,91.56,69.81,41.89,0.98,...,63,0,0.02,0.0,222,0,0.09,0.0,1,1
2,82.0,4,4,1,338.75,112.92,155.14,147.97,67.02,0.99,...,12,0,0.00,0.0,277,0,0.09,0.0,0,1
3,75.0,4,3,1,114.78,38.26,68.19,43.00,32.56,0.97,...,47,1,0.03,0.0,157,0,0.10,0.0,0,0
4,62.0,4,4,1,152.90,50.97,88.47,42.24,33.99,0.97,...,28,0,0.02,0.0,125,0,0.08,0.0,0,1

In [ ]:
df[df.isna().any(axis=1)]

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,tutorial_total_reading_time,tutorial_mean_reading_time,tutorial_max_reading_time,tutorial_median_reading_time,...,memory_not_dominant_hand_y_range,memory_not_dominant_hand_z_range,memory_dominant_hand_trigger_press_count,memory_not_dominant_hand_trigger_press_count,memory_dominant_hand_trigger_pressure_mean,memory_not_dominant_hand_trigger_pressure_mean,memory_dominant_hand_grip_count,memory_not_dominant_hand_grip_count,memory_dominant_hand_grip_mean,memory_not_dominant_hand_grip_mean
0,P001,NaN,Female,Right,4,1,45.03,15.01,21.00,17.23,...,0.80,0.50,35,0,0.01,0.00,1275,0,0.40,0.0
1,P002,59.0,Female,Right,4,3,171.99,57.33,91.56,69.81,...,0.61,1.15,63,0,0.02,0.00,222,0,0.09,0.0
2,P003,82.0,Male,Right,4,4,338.75,112.92,155.14,147.97,...,0.75,0.61,12,0,0.00,0.00,277,0,0.09,0.0
3,P004,75.0,Male,Left,4,3,114.78,38.26,68.19,43.00,...,0.59,0.92,47,1,0.03,0.00,157,0,0.10,0.0
4,P005,62.0,Male,Right,4,4,152.90,50.97,88.47,42.24,...,0.58,0.48,28,0,0.02,0.00,125,0,0.08,0.0
5,P006,78.0,Female,Right,4,3,181.69,60.56,90.17,75.06,...,0.42,0.71,244,0,0.12,0.00,261,0,0.13,0.0
6,P007,71.0,Female,Right,4,3,190.51,63.50,83.86,57.69,...,0.64,0.46,12,0,0.01,0.00,159,0,0.11,0.0
7,P008,69.0,Female,Right,4,4,208.51,69.50,99.78,67.13,...,0.33,0.92,27,0,0.02,0.00,127,0,0.08,0.0
8,P009,73.0,Male,Right,4,2,198.53,66.18,94.27,90.08,...,0.59,0.72,631,0,0.23,0.00,630,0,0.21,0.0
9,P010,81.0,Female,Right,4,3,265.83,88.61,115.47,95.42,...,0.63,0.69,284,0,0.18,0.00,799,0,0.21,0.0
10,P011,74.0,Female,Right,4,3,210.34,70.11,79.48,70.82,...,0.33,0.22,12,0,0.01,0.00,159,0,0.14,0.0
11,P012,65.0,Male,Right,4,3,164.28,54.76,60.26,58.93,...,0.46,0.38,8,0,0.01,0.00,112,0,0.10,0.0
12,P013,61.0,Female,Right,4,3,109.99,36.66,62.12,31.25,...,0.41,0.19,14,0,0.01,0.00,136,0,0.13,0.0
13,P014,79.0,Male,Left,4,1,534.07,178.02,206.77,197.68,...,0.79,0.66,1457,2,0.40,0.00,1545,11,0.44,0.0
14,P015,74.0,Female,Right,4,3,269.98,89.99,180.21,66.22,...,0.38,0.70,46,0,0.04,0.00,173,0,0.15,0.0
15,P016,75.0,Female,Right,4,3,260.47,86.82,122.55,121.28,...,0.47,0.69,65,0,0.03,0.00,136,0,0.11,0.0
16,P017,76.0,Female,Right,4,3,241.54,80.51,184.65,45.79,...,0.49,0.70,10,0,0.01,0.00,233,0,0.18,0.0
17,P018,69.0,Female,Right,4,3,371.73,123.91,194.47,137.26,...,0.70,0.76,58,116,0.03,0.01,171,4,0.13,0.0
18,P019,70.0,Male,Right,4,3,279.39,93.13,178.58,88.00,...,0.54,0.79,284,0,0.20,0.00,273,0,0.20,0.0
19,P020,72.0,Female,Right,4,3,201.54,67.18,95.63,87.69,...,0.41,0.26,57,0,0.03,0.00,250,0,0.18,0.0

## 2.2 Standardize (z-score)

## 2.3 Exploratory Data Analysis

correlation matrix

variance filtering

redundancy detection

## 2.4 Reduce dimensionality (PCA)

## 2.5 Validate

correlation preservation

distribution matching

model stability