# 0. Library

In [25]:
import pandas as pd
from pathlib import Path
import re

import importlib
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp
from features import general_func as gf
import constants_data as cd

# Reload
importlib.reload(du)
importlib.reload(dp)
importlib.reload(gf)
importlib.reload(cd)

# 1. Paths and Constants

In [26]:
# Constants and paths
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv" / "1.extracted_features.csv"

df = pd.read_csv(df_path)

df.head()

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,MoCA_Score,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,P001,NaN,Female,Right,4,4,28.0,1,45.03,15.01,...,0.80,0.50,35,0,0.01,0.0,1275,0,0.40,0.0
1,P002,59.0,Female,Right,4,2,NaN,1,171.99,57.33,...,0.61,1.15,63,0,0.02,0.0,222,0,0.09,0.0
2,P003,82.0,Male,Right,4,1,26.0,1,338.75,112.92,...,0.75,0.61,12,0,0.00,0.0,277,0,0.09,0.0
3,P004,75.0,Male,Left,4,2,NaN,1,114.78,38.26,...,0.59,0.92,47,1,0.03,0.0,157,0,0.10,0.0
4,P005,62.0,Male,Right,4,1,27.0,1,152.90,50.97,...,0.58,0.48,28,0,0.02,0.0,125,0,0.08,0.0

In [27]:
df_cleaning = df.loc[:19].copy() # copy original

In [28]:
df_cleaning

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,MoCA_Score,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,P001,NaN,Female,Right,4,4,28.0,1,45.03,15.01,...,0.80,0.50,35,0,0.01,0.00,1275,0,0.40,0.0
1,P002,59.0,Female,Right,4,2,NaN,1,171.99,57.33,...,0.61,1.15,63,0,0.02,0.00,222,0,0.09,0.0
2,P003,82.0,Male,Right,4,1,26.0,1,338.75,112.92,...,0.75,0.61,12,0,0.00,0.00,277,0,0.09,0.0
3,P004,75.0,Male,Left,4,2,NaN,1,114.78,38.26,...,0.59,0.92,47,1,0.03,0.00,157,0,0.10,0.0
4,P005,62.0,Male,Right,4,1,27.0,1,152.90,50.97,...,0.58,0.48,28,0,0.02,0.00,125,0,0.08,0.0
5,P006,78.0,Female,Right,4,2,27.0,1,181.69,60.56,...,0.42,0.71,244,0,0.12,0.00,261,0,0.13,0.0
6,P007,71.0,Female,Right,4,2,26.0,1,190.51,63.50,...,0.64,0.46,12,0,0.01,0.00,159,0,0.11,0.0
7,P008,69.0,Female,Right,4,1,29.0,1,208.51,69.50,...,0.33,0.92,27,0,0.02,0.00,127,0,0.08,0.0
8,P009,73.0,Male,Right,4,3,NaN,1,198.53,66.18,...,0.59,0.72,631,0,0.23,0.00,630,0,0.21,0.0
9,P010,81.0,Female,Right,4,2,25.0,1,265.83,88.61,...,0.63,0.69,284,0,0.18,0.00,799,0,0.21,0.0
10,P011,74.0,Female,Right,4,2,28.0,1,210.34,70.11,...,0.33,0.22,12,0,0.01,0.00,159,0,0.14,0.0
11,P012,65.0,Male,Right,4,2,29.0,1,164.28,54.76,...,0.46,0.38,8,0,0.01,0.00,112,0,0.10,0.0
12,P013,61.0,Female,Right,4,2,NaN,1,109.99,36.66,...,0.41,0.19,14,0,0.01,0.00,136,0,0.13,0.0
13,P014,79.0,Male,Left,4,4,17.0,1,534.07,178.02,...,0.79,0.66,1457,2,0.40,0.00,1545,11,0.44,0.0
14,P015,74.0,Female,Right,4,2,30.0,1,269.98,89.99,...,0.38,0.70,46,0,0.04,0.00,173,0,0.15,0.0
15,P016,75.0,Female,Right,4,2,NaN,1,260.47,86.82,...,0.47,0.69,65,0,0.03,0.00,136,0,0.11,0.0
16,P017,76.0,Female,Right,4,2,NaN,1,241.54,80.51,...,0.49,0.70,10,0,0.01,0.00,233,0,0.18,0.0
17,P018,69.0,Female,Right,4,2,27.0,1,371.73,123.91,...,0.70,0.76,58,116,0.03,0.01,171,4,0.13,0.0
18,P019,70.0,Male,Right,4,2,NaN,1,279.39,93.13,...,0.54,0.79,284,0,0.20,0.00,273,0,0.20,0.0
19,P020,72.0,Female,Right,4,2,29.0,1,201.54,67.18,...,0.41,0.26,57,0,0.03,0.00,250,0,0.18,0.0

# 2. Data preprocessing

In [29]:
df_cleaning = dp.check_Nan_values(original_df= df_cleaning, missing_values_threshold=0.6, target_col='MoCA_Score')

Missing values found, number of columns with Nan values : 4
{'Age': 1, 'MoCA_Score': 7, 'ObjectRecognition_std_duration_gaze': 6, 'Memory_cognitive_freez_mean_duration': 17}
Removed columns :['Memory_cognitive_freez_mean_duration']
All Nan values are handled successfuly.

In [30]:
df_cleaning = dp.check_columns_type(df_without_Nan= df_cleaning)

Columns before one hot encoding :

          Total columns :376,
          Numerical columns : 373,
          Categorical columns : 3,
          Unkown columns : 0


 Columns after one hot encoding :

          Total columns :375,
          Numerical columns : 375,
          Categorical columns : 0,
          Unkown columns : 0

All Categorical columns are encoded successfuly.

In [31]:
df_cleaning = dp.check_constant_column(df_without_categorical_column=df_cleaning)

Columns before removing constant columns : 375
There are 28 constant columns, removing them...

 Columns after removing constant columns : 347
All constant columns are removed successfuly.

In [32]:
df_cleaning = dp.check_correlation(df_cleaning, "MoCA_Score")

Number of columns before removing 347
No Nan correlation.
Number of small correlation 162
Number of redundant features 65
Number of total useless columns 227, Removing them...
All useless correlations are removed successfully.
Number of columns after removing 120

In [33]:
df_cleaning.head()

,Age,Help_Rating_out_of_5,MoCA_Score,Tutorial_total_reading_time,Tutorial_max_reading_time,Tutorial_intensity_reading_time,Tutorial_total_duration_hover,Tutorial_mean_duration_hover,Tutorial_max_duration_hover,Tutorial_std_duration_hover,...,Memory_Yaw_std,Memory_Pitch_std,Memory_Roll_std,Memory_Yaw_range,Memory_dominant_hand_mean_speed,Memory_not_dominant_hand_mean_speed,Memory_dominant_hand_z_range,Memory_not_dominant_hand_y_range,Gender_Male,dominant_hand_Right
0,73.0,4,28.0,45.03,21.00,0.92,20.64,1.03,2.29,0.74,...,26.23,161.72,177.36,99.05,0.16,0.03,0.82,0.80,0,1
1,59.0,2,27.0,171.99,91.56,0.98,53.05,1.02,13.42,2.25,...,47.08,165.33,172.85,180.39,0.06,0.04,1.02,0.61,0,1
2,82.0,1,26.0,338.75,155.14,0.99,145.79,2.11,20.01,4.20,...,23.27,161.90,162.61,109.38,0.06,0.01,0.98,0.75,1,1
3,75.0,2,27.0,114.78,68.19,0.97,46.90,1.47,13.24,2.97,...,25.75,171.61,101.97,234.99,0.06,0.03,0.50,0.59,1,0
4,62.0,1,27.0,152.90,88.47,0.97,54.33,1.81,11.62,2.66,...,30.07,170.64,169.17,248.93,0.12,0.02,1.05,0.58,1,1

In [35]:
df_cleaning.shape

(20, 120)

In [36]:
# save df
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv"
name = "2.cleaned_features_20_patients.csv"
df_cleaning.to_csv(df_path / name, index=False)