# Solution two : 2 Feature Selection + data augmentation + Train + log to MLFlow

# 0.Library

In [5]:
# general
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import re
import importlib

# ML
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import LeaveOneOut, cross_validate
from sklearn.pipeline import Pipeline

# MLFlow
import mlflow
import mlflow.sklearn
from mlflow.tracking import MlflowClient

# Paths
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp
from features import general_func as gf
import constants_data as cd
from features import model_utils as mu
import paths_data as paths

# Reload
importlib.reload(du)
importlib.reload(dp)
importlib.reload(gf)
importlib.reload(cd)
importlib.reload(mu)
importlib.reload(paths)

# 1. Paths and Constants

In [6]:
# Read dataframe
models_paths_folder = paths.MODELS_DIR_SOL_TWO

# Read dataframe input (train set)
name_input_df = "cleaned_features_13_patients.csv"
df_path = paths.STAGE_THREE_DATA_PREPROCESSING/ name_input_df
df      = pd.read_csv(df_path)
df.head()

,Age,Help_Rating_out_of_5,MoCA_Score,Tutorial_total_reading_time,Tutorial_intensity_reading_time,Tutorial_total_count_hover,Tutorial_total_duration_hover,Tutorial_mean_duration_hover,Tutorial_max_duration_hover,Tutorial_total_count_press,...,Memory_Yaw_std,Memory_Pitch_std,Memory_Roll_std,Memory_Yaw_range,Memory_Roll_range,Memory_dominant_hand_mean_speed,Memory_not_dominant_hand_mean_speed,Memory_dominant_hand_z_range,Memory_not_dominant_hand_y_range,Gender_Male
0,73.0,4,28.0,45.03,0.92,32,20.64,1.03,2.29,8,...,26.23,161.72,177.36,99.05,360.00,0.16,0.03,0.82,0.80,0
1,82.0,1,26.0,338.75,0.99,688,145.79,2.11,20.01,9,...,23.27,161.90,162.61,109.38,359.99,0.06,0.01,0.98,0.75,1
2,62.0,1,27.0,152.90,0.97,61,54.33,1.81,11.62,8,...,30.07,170.64,169.17,248.93,359.98,0.12,0.02,1.05,0.58,1
3,78.0,2,27.0,181.69,0.98,26,91.62,2.78,23.45,9,...,31.96,136.51,170.83,174.64,359.98,0.12,0.02,0.82,0.42,0
4,71.0,2,26.0,190.51,0.98,109,102.68,2.57,21.86,8,...,27.48,169.32,125.66,146.78,359.99,0.11,0.03,0.82,0.64,0

# 3. Data Splitting

In [7]:
y = df['MoCA_Score']
df = df.drop(columns=['MoCA_Score'])
X = df

# 4. Train and Test

In [8]:
cd.all_experiments_sol_2

[('gaussian_noise',
  [('LinearRegression', sklearn.linear_model._base.LinearRegression),
   ('Ridge', sklearn.linear_model._ridge.Ridge),
   ('RandomForest', <function constants_data.<lambda>()>),
   ('XGBRegressor', <function constants_data.<lambda>()>),
   ('SVR', sklearn.svm._classes.SVR),
   ('Lasso', sklearn.linear_model._coordinate_descent.Lasso)]),
 ('smoter',
  [('LinearRegression', sklearn.linear_model._base.LinearRegression),
   ('Ridge', sklearn.linear_model._ridge.Ridge),
   ('RandomForest', <function constants_data.<lambda>()>),
   ('XGBRegressor', <function constants_data.<lambda>()>),
   ('SVR', sklearn.svm._classes.SVR),
   ('Lasso', sklearn.linear_model._coordinate_descent.Lasso)]),
 ('gaussian_copula',
  [('LinearRegression', sklearn.linear_model._base.LinearRegression),
   ('Ridge', sklearn.linear_model._ridge.Ridge),
   ('RandomForest', <function constants_data.<lambda>()>),
   ('XGBRegressor', <function constants_data.<lambda>()>),
   ('SVR', sklearn.svm._classes.SVR),
   ('Lasso', sklearn.linear_model._coordinate_descent.Lasso)])]

In [9]:
def rescale_func(X_train, X_test):
    from sklearn.preprocessing import StandardScaler

    # create transformer
    scaler = StandardScaler()
    scaler.fit(X_train)

    return scaler.transform(X_train), scaler.transform(X_test)

In [23]:
original_cols = X.columns.to_list()
original_cols

['Age',
 'Help_Rating_out_of_5',
 'Tutorial_total_reading_time',
 'Tutorial_intensity_reading_time',
 'Tutorial_total_count_hover',
 'Tutorial_total_duration_hover',
 'Tutorial_mean_duration_hover',
 'Tutorial_max_duration_hover',
 'Tutorial_total_count_press',
 'Tutorial_median_duration_press',
 'Tutorial_total_duration_grab',
 'Tutorial_total_count_gaze',
 'Tutorial_max_duration_gaze',
 'Tutorial_median_duration_gaze',
 'Tutorial_intensity_gaze',
 'Tutorial_decision_latency',
 'Tutorial_head_total_distance',
 'Tutorial_HMD_Y_std',
 'Tutorial_HMD_Z_std',
 'Tutorial_HMD_Y_range',
 'Tutorial_head_total_orientation',
 'Tutorial_Yaw_std',
 'Tutorial_Roll_std',
 'Tutorial_Pitch_range',
 'Tutorial_Roll_range',
 'Tutorial_max_head_speed_in_orientation',
 'Tutorial_not_dominant_hand_mean_speed',
 'Tutorial_dominant_hand_max_speed',
 'Tutorial_dominant_hand_x_range',
 'Tutorial_not_dominant_hand_x_range',
 'Tutorial_dominant_hand_trigger_press_count',
 'Tutorial_dominant_hand_trigger_pressure_mean',
 'Tutorial_dominant_hand_grip_count',
 'ObjectRecognition_total_reading_time',
 'ObjectRecognition_mean_reading_time',
 'ObjectRecognition_max_reading_time',
 'ObjectRecognition_intensity_reading_time',
 'ObjectRecognition_intensity_hover',
 'ObjectRecognition_gaze_happened',
 'ObjectRecognition_total_count_gaze',
 'ObjectRecognition_total_duration_gaze',
 'ObjectRecognition_median_duration_gaze',
 'ObjectRecognition_intensity_gaze',
 'ObjectRecognition_time_before_first_press',
 'ObjectRecognition_head_total_distance',
 'ObjectRecognition_HMD_Y_range',
 'ObjectRecognition_HMD_Z_range',
 'ObjectRecognition_mean_head_speed_in_distance',
 'ObjectRecognition_std_head_speed_in_distance',
 'ObjectRecognition_Yaw_std',
 'ObjectRecognition_Pitch_std',
 'ObjectRecognition_Roll_std',
 'ObjectRecognition_Roll_range',
 'ObjectRecognition_mean_head_speed_in_orientation',
 'ObjectRecognition_dominant_hand_z_range',
 'ObjectRecognition_dominant_hand_grip_count',
 'Visuospatial_total_reading_time',
 'Visuospatial_total_duration_hover',
 'Visuospatial_median_duration_hover',
 'Visuospatial_intensity_press',
 'Visuospatial_total_count_grab',
 'Visuospatial_intensity_grab',
 'Visuospatial_total_count_gaze',
 'Visuospatial_median_duration_gaze',
 'Visuospatial_hover_vs_active_interaction_ratio',
 'Visuospatial_clicks_per_second',
 'Visuospatial_head_total_distance',
 'Visuospatial_HMD_Y_std',
 'Visuospatial_HMD_Z_std',
 'Visuospatial_HMD_Y_range',
 'Visuospatial_HMD_Z_range',
 'Visuospatial_mean_head_speed_in_distance',
 'Visuospatial_Yaw_std',
 'Visuospatial_Roll_std',
 'Visuospatial_Pitch_range',
 'Visuospatial_mean_head_speed_in_orientation',
 'Visuospatial_max_head_speed_in_orientation',
 'Visuospatial_dominant_hand_total_distance',
 'Visuospatial_dominant_hand_x_range',
 'Visuospatial_dominant_hand_y_range',
 'Visuospatial_dominant_hand_grip_mean',
 'Memory_median_reading_time',
 'Memory_intensity_reading_time',
 'Memory_mean_duration_hover',
 'Memory_max_duration_hover',
 'Memory_intensity_hover',
 'Memory_total_count_press',
 'Memory_median_duration_press',
 'Memory_mean_duration_gaze',
 'Memory_max_duration_gaze',
 'Memory_intensity_gaze',
 'Memory_decision_latency',
 'Memory_clicks_per_second',
 'Memory_time_before_first_press',
 'Memory_score',
 'Memory_delay_first_action',
 'Memory_head_total_distance',
 'Memory_HMD_X_std',
 'Memory_HMD_Y_std',
 'Memory_HMD_X_range',
 'Memory_HMD_Z_range',
 'Memory_max_head_speed_in_distance',
 'Memory_Yaw_std',
 'Memory_Pitch_std',
 'Memory_Roll_std',
 'Memory_Yaw_range',
 'Memory_Roll_range',
 'Memory_dominant_hand_mean_speed',
 'Memory_not_dominant_hand_mean_speed',
 'Memory_dominant_hand_z_range',
 'Memory_not_dominant_hand_y_range',
 'Gender_Male']

In [24]:
X_train =X.iloc[:11]
y_train = y.iloc[:11]

X_test =X.iloc[[-1]]
y_test = y.iloc[[-1]]

In [21]:
type(X_test)

pandas.core.frame.DataFrame

In [25]:
X_train_scaled, X_test_scaled = rescale_func(X_train, X_test)

In [30]:
X_new, y_new = dp.guassian_noise_pipeline(mean = 0.0, standard_deviation=1.0, 
                            X_train_scaled= X_train_scaled, y_train= y_train,
                            original_cols= X.columns.to_list())

In [34]:
X_train.shape

(11, 112)

In [33]:
y_new.shape

(22,)

In [31]:
X_new.shape

(22, 112)

In [35]:
X_new

,Age,Help_Rating_out_of_5,Tutorial_total_reading_time,Tutorial_intensity_reading_time,Tutorial_total_count_hover,Tutorial_total_duration_hover,Tutorial_mean_duration_hover,Tutorial_max_duration_hover,Tutorial_total_count_press,Tutorial_median_duration_press,...,Memory_Yaw_std,Memory_Pitch_std,Memory_Roll_std,Memory_Yaw_range,Memory_Roll_range,Memory_dominant_hand_mean_speed,Memory_not_dominant_hand_mean_speed,Memory_dominant_hand_z_range,Memory_not_dominant_hand_y_range,Gender_Male
0,-0.074387,1.917029,-1.576088,-2.996604,-0.472173,-1.664867,-1.871021,-1.639980,-0.693375,-0.860170,...,-0.560862,0.128516,0.955211,-1.086911,1.206241,0.951842,0.912871,-0.880177,1.420797,-0.755929
1,1.398475,-1.095445,0.888014,0.665912,3.022394,1.496167,-0.401905,0.164100,0.832050,-0.413855,...,-0.787294,0.146525,0.494884,-0.988323,0.748701,-1.665723,-1.095445,-0.064855,1.130299,1.322876
2,-1.874552,-1.095445,-0.671136,-0.380521,-0.317688,-0.813926,-0.809992,-0.690089,-0.693375,-0.279961,...,-0.267114,1.020944,0.699612,0.343528,0.291162,-0.095184,-0.091287,0.291848,0.142608,1.322876
3,0.743870,-0.091287,-0.429608,0.142695,-0.504136,0.127943,0.509491,0.514328,0.832050,0.077091,...,-0.122534,-2.393693,0.751418,-0.365488,0.291162,-0.095184,-0.091287,-0.880177,-0.786984,-0.755929
4,-0.401690,-0.091287,-0.355614,0.142695,-0.061988,0.407296,0.223830,0.352449,-0.693375,-0.146067,...,-0.465241,0.888881,-0.658275,-0.631381,0.748701,-0.356941,0.912871,-0.880177,0.491205,-0.755929
5,-0.728992,-1.095445,-0.204607,0.142695,-0.562734,0.641943,1.801770,0.988764,-0.693375,-0.592381,...,-0.777349,-0.748905,0.957707,-1.040051,-1.081457,-1.403966,0.912871,-1.644541,-1.309879,-0.755929
6,1.234824,-0.091287,0.276267,0.665912,-0.344323,0.347435,1.271255,-0.040539,2.357476,-0.146067,...,-0.126359,0.363629,-0.369595,1.368448,-0.623918,0.166572,-1.095445,0.903339,0.433105,-0.755929
7,0.089264,-0.091287,-0.189255,0.142695,-0.397594,-0.797761,-0.687566,-0.738958,-0.693375,-0.235329,...,0.462668,-1.084065,0.615349,1.318820,0.748701,0.951842,-1.095445,-0.319643,-1.309879,-0.755929
8,-1.383598,-0.091287,-0.575666,0.142695,-0.365632,-0.665410,-0.116243,-0.539410,-0.693375,-0.369224,...,2.978656,-0.040565,0.211509,1.377419,-0.166378,0.690085,-0.091287,0.393763,-0.554586,1.322876
9,0.907521,1.917029,2.526610,0.665912,0.529318,1.707323,0.754344,2.276665,0.832050,3.067398,...,-0.175317,1.021945,-2.135691,0.734256,0.291162,-0.880453,-1.095445,1.361958,1.362697,1.322876
10,0.089264,-0.091287,0.311083,0.665912,-0.525444,-0.786143,-0.673963,-0.647329,-0.693375,-0.101435,...,-0.159253,0.696789,-1.522130,-1.030316,-2.454076,1.737111,1.917029,1.718661,-1.019382,-0.755929
0,0.020330,2.561605,-1.004709,-3.267660,0.947782,-1.745940,-1.781525,-1.283702,-0.750936,-2.539447,...,-2.116008,-0.965271,1.816984,2.776568,0.862992,0.860313,1.110731,-0.894988,1.707890,0.268250
1,0.486972,-2.203302,2.954427,-0.714121,2.624362,0.579295,-0.554725,0.910017,-0.276148,-1.719730,...,-1.834552,-0.249634,-0.247129,-2.459244,0.876077,-2.729432,-2.280412,-0.148927,1.918347,2.524388
2,-4.585050,-0.459115,-1.577157,-0.768036,-0.381168,-1.396001,0.353582,-0.866607,-1.479258,1.009363,...,0.170151,1.952072,0.603514,-0.836020,0.326677,0.800639,0.943639,-0.123478,0.953706,2.356071
3,0.840534,-3.173418,-0.362424,-2.621423,-0.992913,1.321980,2.263053,0.265750,1.092726,-0.117364,...,-1.136163,-4.327281,-0.070894,-0.833680,0.532907,-0.359916,-0.896193,-1.562998,-0.071149,-3.241456
4,-1.034768,-1.102516,-1.078275,-0.099885,0.762306,-0.822713,1.191850,-1.513720,-1.836602,1.543440,...,-0.374783,-0.380466,0.827920,0.361532,1.975656,0.964232,1.836164,-0.448774,0.165050,-2.440222
5,-0.157247,-1.522300,0.314828,-0.595038,-0.149366,1.762624,1.827881,2.612577,0.389296,-0.347604,...,0.235619,-1.663056,-0.150537,0.359789,-1.955518,-1.672096,3.152338,-0.982932,-0.815158,0.225145
6,2.028385,1.698432,0.349454,2.214334,1.062436,-0.091087,3.402690,-0.174706,-0.329175,-0.191534,...,-0.853750,-0.605394,-0.510120,1.037151,-0.362345,0.874816,-2.698513,-1.142080,-0.493638,-0.844966
7,0.126711,0.503463,0.712493,-0.783679,-1.084087,-2.791532,-1.093664,-2.213633,-1.792299,0.394336,...,2.424057,-1.633222,-0.221350,-0.973096,1.996180,2.096922,-1.627866,0.161722,-1.944811,0.318396
8,-1.391160,-0.121023,1.405186,0.085160,-0.732465,-0.826145,0.699199,-0.599955,-0.189125,-0.853388,...,4.058558,0.070005,0.959211,1.635816,0.634858,1.274508,1.129226,-0.344545,-0.399209,-0.049291
9,-0.424504,1.248198,2.125757,1.021110,0.529432,0.905547,0.328311,0.365278,0.954972,2.886706,...,0.547168,0.042360,-2.836315,-0.372682,0.301378,-1.439478,-1.262209,0.572539,3.111488,1.728389
10,-0.389114,-0.036051,1.877758,1.805683,-0.855716,-0.019244,0.777621,-0.517571,0.525379,-1.035207,...,0.671542,0.420542,-2.042347,-2.455123,-3.661731,1.297142,3.120400,-0.604877,1.203228,-3.506598

In [ ]:
# experiment list
experiments_list = cd.all_experiments_sol_2

for exp_name, models_list in experiments_list:
    
    print(f"======== Experiment: {exp_name} ===========")
    mlflow.set_experiment(f"MoCA_Regression_data_augmentation_{exp_name}")

    for model in models_list:
        print(f"================ Run: {exp_name}_{model.__name__} =================")
        with mlflow.start_run(run_name=f"{exp_name}_{model.__name__}"):

            pipe = mu.make_model_pipeline(
                mu.make_feature_pipeline(exp_name, k_value),
                model()
            )

            scores = cross_validate(
                pipe,
                X,
                y,
                cv=5,
                scoring={
                    "r2": "r2",
                    "mae": "neg_mean_absolute_error",
                    "mse": "neg_mean_squared_error",
                    "rmse": "neg_root_mean_squared_error"
                },
                return_train_score=True
            )

            # compute metrics of test set
            r2_test   = scores["test_r2"].mean()
            mae_test  = -scores["test_mae"].mean()
            mse_test  = -scores["test_mse"].mean()
            rmse_test = -scores["test_rmse"].mean()

            # compute metrics of train set
            r2_train   = scores["train_r2"].mean()
            mae_train  = -scores["train_mae"].mean()
            mse_train  = -scores["train_mse"].mean()
            rmse_train = -scores["train_rmse"].mean()

            # print
            print(f"Model: {model.__name__}")
            print(f"R² of test: {mse_test:.3f}")

            # MLflow logging
            mlflow.log_param("experiment", exp_name)
            mlflow.log_param("model", model.__name__)

            mlflow.log_metric("r2_test", r2_test)
            mlflow.log_metric("mae_test", mae_test)
            mlflow.log_metric("mse_test", mse_test)
            mlflow.log_metric("rmse_test", rmse_test)

            mlflow.log_metric("r2_test", r2_train)
            mlflow.log_metric("mae_test", mae_train)
            mlflow.log_metric("mse_test", mse_train)
            mlflow.log_metric("rmse_test", rmse_train)

            mlflow.log_metric("gap", abs(mse_test - mse_train))

            # log model
            mlflow.sklearn.log_model(pipe, name="model", skops_trusted_types=["xgboost.sklearn.XGBRegressor", "sklearn.feature_selection._univariate_selection.f_regression"])

## 5.0 Split train/test and Scale

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

scaler = StandardScaler()
scaler.fit(X_train)

In [ ]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 5.1 Gaussian noise

In [ ]:
X_train_aug , y_train_aug = du.guassian_noise_pipeline(loc=0, scale=1, 
                                                       X_train_scaled= X_train_scaled, y_train= y_train, 
                                                       original_cols= X_train.columns)

In [ ]:
X_train_aug.shape , y_train_aug.shape

## 5.2 SMOTER

In [ ]:
import numpy as np

Q1 = np.quantile(y_train, 0.25)
Q2 = np.quantile(y_train, 0.50)  # median
Q3 = np.quantile(y_train, 0.75)

print("Q1:", Q1)
print("Q2:", Q2)
print("Q3:", Q3)

IQR = Q3 - Q1

lower_fence = Q1 - 1.5 * IQR
upper_fence = Q3 + 1.5 * IQR

print("lower_fence:",lower_fence)
print("upper_fence:", upper_fence)