# 0.Library

In [1]:
# general
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import importlib
import joblib


# Paths
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp
from features import general_func as gf
import constants_data as cd

# Reload
importlib.reload(du)
importlib.reload(dp)
importlib.reload(gf)
importlib.reload(cd)

# 1. Paths and Constants

In [3]:
parent_folder = Path("../..") # go 2 folder up= "../.."

# Read models path
models_paths_folder = parent_folder / "models" / "solution_one"
best_model = "SelectKBest_SVR_20.pkl"

# Read dataframe input (test set)
df_path = parent_folder / "data" / "produced_csv" / "3.output_nb_3.Model_designing_solution_one" / "3.cleaned_features_20_young_patients.csv"
df      = pd.read_csv(df_path)
df.head()

#X = df.drop(columns=['MoCA_Score'])
X = df.copy()

FileNotFoundError: [Errno 2] No such file or directory: '../../data/produced_csv/3.output_nb_3.Model_designing_solution_one/3.cleaned_features_20_young_patients.csv'

# 2. Predict MoCA score by best model

In [ ]:
# Read the best model
path_best_model = models_paths_folder / best_model 
loaded_model = joblib.load(path_best_model)

In [5]:
loaded_model

Pipeline(steps=[('features',
                 Pipeline(steps=[('scaler', StandardScaler()),
                                 ('select',
                                  SelectKBest(k=20,
                                              score_func=<function f_regression at 0x7ccba570e6c0>))])),
                ('model', SVR())])

In [10]:
model_svr = loaded_model['model']
model_svr

SVR()

In [11]:
loaded_model['model'].dual_coef_

array([[ 0.92556628, -1.        , -1.        , -0.25407324, -1.        ,
         1.        , -1.        ,  0.15098304,  1.        , -1.        ,
         1.        ,  0.17752392,  1.        ]])

In [13]:
loaded_model['model'].support_vectors_

array([[-1.68728842, -1.82026736, -0.85691868, -0.42996873, -1.32210348,
        -0.85342795, -0.95236351,  0.07099137, -0.67219459, -1.33880218,
         1.49495275, -1.11576979, -1.20385853,  1.04480502,  1.60560936,
        -0.70246821, -0.62963848, -0.68347779,  0.41441642,  1.45404193],
       [ 0.83947855,  0.03273891, -0.38085275, -0.12593967,  0.56194073,
        -0.59884605, -0.9065768 , -0.35470016,  0.26704288, -0.46077609,
        -0.38579426, -0.62789793,  0.36115756,  0.58930725, -0.28901626,
         0.41344636,  2.75587447,  0.17852032,  0.31646345,  1.1568321 ],
       [-0.75932181, -0.84461564, -0.23803297, -0.32675809,  0.07087372,
        -0.85053497, -0.65932858, -0.76990433, -0.98620227,  0.41725001,
         0.24112141, -0.24494476, -0.42135049,  0.89952393, -0.24416041,
        -0.46343212, -0.41323631,  0.70898069,  0.20070084,  0.14631868],
       [-0.51165185,  0.39246473,  0.14281978, -0.92154627, -0.2451595 ,
         0.41948153,  0.44870973, -0.36614092,  0.02596602, -0.71442807,
        -0.38579426,  0.41079698, -0.42135049,  1.24459185, -0.08396095,
         1.30147161, -0.01681819, -0.81609288,  1.04665833, -0.80475276],
       [-0.43577658,  0.22619611, -0.09521319,  0.4148841 , -0.72407138,
        -0.3992307 , -0.14651746, -0.59447937, -0.85832011, -0.09005396,
         1.49495275, -0.9478999 ,  1.1436656 , -1.62476042, -0.52397547,
        -1.12769648, -0.02671268,  0.97421088, -0.67642349,  0.50297048],
       [-0.28092909,  0.87976774, -0.57127912, -0.82659248, -0.8042952 ,
        -0.72324402, -0.92489148, -0.11396755, -0.39262647,  0.33920324,
         0.86803708, -0.43379838, -0.42135049,  0.40876966, -1.08146959,
        -1.34732894, -0.39759663, -1.14763062, -1.39771356, -1.33973045],
       [ 0.21217415, -0.17744972, -0.09521319, -0.88144157, -0.57334785,
         0.73192295,  1.83146828, -0.33420214, -0.27436713,  0.2221331 ,
        -0.38579426,  1.56490243,  0.36115756, -0.72247769,  0.30265375,
         0.34285022, -0.38482954, -0.08670987,  0.9709674 ,  0.44352851],
       [-0.26518626, -0.89480994, -0.19042637,  0.69915569, -0.04824649,
        -0.32401332,  0.72342997, -0.11444425, -0.28728196, -0.63638131,
         0.24112141,  0.15899215, -0.42135049,  1.19636745, -0.73543875,
        -0.67274351, -0.44164309, -0.35194006, -0.68532831, -1.33973045],
       [-0.66142379, -0.68984988, -0.33324615,  0.76255652, -0.37400381,
        -0.58727415, -0.95236351, -0.52869502, -0.95074979, -0.38272932,
         0.86803708, -0.95314584, -1.20385853, -0.18957772, -0.77175063,
        -0.45063399, -0.2788627 ,  0.44375051, -1.20626002, -0.5669849 ],
       [ 2.5197459 ,  2.20259671,  3.33246153,  2.8730667 ,  2.83008685,
         1.92093612,  1.48348931,  3.03128744,  3.02195376,  3.0318166 ,
        -2.26654126,  2.56162987,  2.70868169, -1.95361846,  2.46641446,
         2.55073447,  1.73482649,  2.43297691,  2.38238067,  1.39459996],
       [ 0.2478751 , -0.80069563, -0.04760659, -0.24448446,  0.71752632,
        -0.15622071, -0.95236351, -0.38473215,  0.28603528, -0.49979947,
        -0.38579426, -0.00887773,  0.36115756, -0.2203765 ,  0.67858848,
        -0.1327449 , -0.58208107, -0.02040232, -0.46716033, -1.04252063],
       [ 1.12319357,  0.94251061, -0.66649231, -0.08819406,  0.54735458,
         2.23048456,  1.3278145 , -0.75274319,  0.40201553, -0.2071241 ,
        -0.38579426, -0.3131419 , -0.42135049, -0.73341937, -0.36164001,
         0.16986901, -0.51952233,  0.04590522, -0.36030254,  0.85962227],
       [-0.34088948,  0.55141335,  0.        , -0.90473768, -0.63655449,
        -0.8100333 , -0.32050695,  1.21173026,  0.41872884,  0.31969155,
        -1.01270993, -0.05084521, -0.42135049,  0.060865  , -0.96185399,
         0.11867648, -0.79975995, -1.67809099, -0.53839885, -0.86419473]])

In [32]:
y_pred = loaded_model.predict(X)

In [33]:
y_pred

array([27.46725233, 27.57951694, 28.01306912, 27.05992514, 28.03651433,
       27.9082486 , 27.99688406, 27.56882485, 27.2993215 , 28.06438651,
       28.00146339, 27.50901274, 27.42220401, 27.47599139, 27.83084145,
       27.58130601, 27.90639753, 27.64790664, 27.68969851, 27.68235225])

In [34]:
df['Predicted_MoCA'] = y_pred
df.head()

,Age,Help_Rating_out_of_5,Tutorial_total_reading_time,Tutorial_intensity_reading_time,Tutorial_total_count_hover,Tutorial_total_duration_hover,Tutorial_mean_duration_hover,Tutorial_max_duration_hover,Tutorial_total_count_press,Tutorial_median_duration_press,...,Memory_Pitch_std,Memory_Roll_std,Memory_Yaw_range,Memory_Roll_range,Memory_dominant_hand_mean_speed,Memory_not_dominant_hand_mean_speed,Memory_dominant_hand_z_range,Memory_not_dominant_hand_y_range,Gender_Male,Predicted_MoCA
0,22.0,0,32.97,0.89,12,24.95,1.39,5.69,8,0.14,...,168.53,174.12,93.06,359.98,0.26,0.03,0.68,0.11,1,27.467252
1,23.0,0,28.38,0.88,14,15.30,0.70,2.60,8,0.10,...,133.18,160.58,143.37,359.99,0.17,0.01,0.74,0.03,1,27.579517
2,23.0,0,52.16,0.93,59,16.58,0.55,2.52,8,0.10,...,148.71,173.85,95.19,359.98,0.18,0.03,0.71,0.45,1,28.013069
3,22.0,1,40.72,0.91,22,25.25,1.26,4.09,8,0.14,...,169.39,165.91,98.49,359.91,0.10,0.02,0.56,0.55,1,27.059925
4,22.0,0,60.58,0.94,21,16.58,0.87,5.96,8,0.14,...,169.60,165.21,82.38,359.95,0.21,0.11,0.68,0.19,1,28.036514

In [35]:
#df[['MoCA_Score','Predicted_MoCA']]
df['Predicted_MoCA']

0     27.467252
1     27.579517
2     28.013069
3     27.059925
4     28.036514
5     27.908249
6     27.996884
7     27.568825
8     27.299321
9     28.064387
10    28.001463
11    27.509013
12    27.422204
13    27.475991
14    27.830841
15    27.581306
16    27.906398
17    27.647907
18    27.689699
19    27.682352
Name: Predicted_MoCA, dtype: float64

# 3. Convert MoCa score to severity level

In [36]:
#df['severity_level'] = df['MoCA_Score'].apply(du.severity_level_MoCA)
df['predicted_severity_level'] = df['Predicted_MoCA'].apply(du.severity_level_MoCA)

In [37]:
#df[['MoCA_Score','severity_level','predicted_severity_level','Predicted_MoCA']]
df[['predicted_severity_level','Predicted_MoCA']]

   predicted_severity_level  Predicted_MoCA
0                    Normal       27.467252
1                    Normal       27.579517
2                    Normal       28.013069
3                    Normal       27.059925
4                    Normal       28.036514
5                    Normal       27.908249
6                    Normal       27.996884
7                    Normal       27.568825
8                    Normal       27.299321
9                    Normal       28.064387
10                   Normal       28.001463
11                   Normal       27.509013
12                   Normal       27.422204
13                   Normal       27.475991
14                   Normal       27.830841
15                   Normal       27.581306
16                   Normal       27.906398
17                   Normal       27.647907
18                   Normal       27.689699
19                   Normal       27.682352

In [38]:
name = f"4.cleaned_features_20_young_patients_with_target.csv"

# save df
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv"
df.to_csv(df_path / name, index=False)